### ISSUE TITLE
Reference QR codes are currently not validated

### ISSUE THREAD

**Issue by sprain** [sprain/php-swiss-qr-bill#10]
https://validation.iso-payments.ch

The platform to officially validate the qr codes currently reports:
`Due to technical problems it is currently not possible to validate Swiss QR Codes`

Before those tests are done, no v1.0 of this library can be released.

**Comment by gexclaude** [comment]
We reported the error on 12 december.

At the moment you could use http://swiss-qr-invoice.org/validator/?lang=de - although this is not the official validation platform, it may give you some hints. We may provide a validation in our demo app as well, although this is not there yet. http://demo.qr-invoice.ch

**Comment by sprain** [comment]
Thanks!

**Comment by gexclaude** [comment]
FYI: https://validation.iso-payments.ch/qrrechnung is again up and running

And our December release is already valid ;) https://www.qr-invoice.ch/2019/01/04/swiss-qr-code-2-0-validation-erfolgreich-durchgefuehrt/

**Comment by sprain** [comment]
Thanks! It looks like my login got disabled and I don't receive their reset-password-mails. Well, I'll look into it …

**Comment by sprain** [comment]
Done. QR codes are successfully validated.
https://github.com/sprain/php-swiss-qr-bill/commit/6619f1febdbbfccb3bb8f20ea042182ec61a8209
