### ISSUE TITLE
No reference, normal IBAN

### ISSUE THREAD

**Issue by wurschmedia** [sprain/php-swiss-qr-bill#100]
Is there a way to skip the reference number and use a normal IBAN (replacement for the red invoice slip) ?
Right now it throws an error if I just delete the $qrBill->setPaymentReference() section

**Comment by wurschmedia** [comment]
Found the answer myself :-)

// Add payment reference
// Explicitly define that no reference number will be used by setting TYPE_NON.
$qrBill->setPaymentReference(
    QrBill\DataGroup\Element\PaymentReference::create(
        QrBill\DataGroup\Element\PaymentReference::TYPE_NON
    ));

**Comment by sprain** [comment]
Normal IBANs can be used when using references of type SCOR or NON.

See these examples:
https://github.com/sprain/php-swiss-qr-bill/blob/master/example/example_minimal.php
https://github.com/sprain/php-swiss-qr-bill/blob/master/example/example_scor.php

**Comment by garga11** [comment]
Hi,  thankyou for your work, I've only a question ... wat I need to change for use the example_scor.php ?
my qr is generated only with  the BESR number, in my case I've only a normal IBAN and no reference...
Thankyou

**Comment by kohlerdominik** [comment]
@garga11 you probably want to use [example_minimal.php](https://github.com/sprain/php-swiss-qr-bill/blob/master/example/example_minimal.php), with the `PaymentReference::TYPE_NON`.

**Comment by garga11** [comment]
thankyou Dominik, exactly, my questione is how can I use example_minimal.php ? I 've to copy the code in another file? thankyou

**Comment by garga11** [comment]
Thnakyou Dominik, 
I don't have composer, but I've solved
only modifing this file app/Helpers/SwissQrGenerator.php at line 78 inserting this:

$qrBill->setCreditorInformation(
    QrBill\DataGroup\Element\CreditorInformation::create(
        'CHXXXXXXXXXXXXX' // This is a classic iban. QR-IBANs will not be valid in this minmal setup.
    )    
);
