### ISSUE TITLE
How can I generate a bill with a a free amount-field

### ISSUE THREAD

**Issue by pnussbaumer** [sprain/php-swiss-qr-bill#103]
I will create a bill with referenz and deptor, but with a free Filed for the amount. so the deptor has the possibillity to pay more then  the amount in the bill.
![QR_ohne_Betrag](https://user-images.githubusercontent.com/74920754/99983148-c86a4f80-2dab-11eb-9fc4-97726db463fc.jpg)

**Comment by pnussbaumer** [comment]
Sorry I see the example with NULL as amount and it works.
At thius time many thanks for this fine library.

**Comment by sprain** [comment]
Exactly,  in this case you do not define an amount, just a currency:

```
$qrBill->setPaymentAmountInformation(
    QrBill\DataGroup\Element\PaymentAmountInformation::create(
        'CHF'
    ));
```
