### ISSUE TITLE
Problem with chars like äöüéàè

### ISSUE THREAD

**Issue by PSchuetz** [sprain/php-swiss-qr-bill#111]
First of all, thanks for this precious library!

Issue: 
HTML and FPDF versions does not work (I've not tried TcPdfOutput), by using German Umlauts and French sings like àéè 
in setCreditor, setUltimateDebtor or setAdditionalInformation.
The Linux server is configured in UTF-8. PHP Version 7.3.27

Example: 
HTML with Creditor "psc Peter Schuetz" works fine: https://feiertagskalender.ch/pdf_rechnung3.php
HTML with Creditor "psc Peter Schütz" produces an error: https://feiertagskalender.ch/pdf_rechnung3a.php
(getViolations() output is included)

I have searched and tried for hours, but can't manage to fix the problem.

**Comment by sprain** [comment]
@Franco2911 You know your way around FPDF. Any ideas?

**Comment by sprain** [comment]
The HtmlOutput is supposed to be placed within an existing html setup. Does this contain `<meta charset="utf-8">` in the header? So something like:

```html
<html>
    <head>
        <meta charset="utf-8">
    </head>
    <body>
        [ html bill output goes here ] 
    </body>
</html>
```

**Comment by PSchuetz** [comment]
Thanks for you support. 

Yesterday I didn't have a header in the HTML, but because the server is completely set to UTF-8, I think it should have worked without one. In the meantime, I have added a UTF-8 header to the HTML, but the problem still occurs, as you can see in the updated example pdf_rechnung3a.php above.

The FPDF I created is completely formatted in UTF-8 and the problem is identical there.

Does it work with umlauts for you? If you create an example, e.g. with postcode "8000 Zürich"?

**Comment by sprain** [comment]
Your `pdf_rechnung3a.php`  does not provide the actual output of `getViolations()`. You can display it like this:

``` php
foreach($qrBill->getViolations() as $violation) {
    print $violation->getMessage()."\n";
}
```

Umlaute are aboslutely no problem where I personally use this library. I use `HtmlOutput`, too.

**Comment by PSchuetz** [comment]
The pdf_rechnung3a.php file contains getViolations() for the QR code graphics (where I thought the problem would arise). 

I added https://feiertagskalender.ch/pdf_rechnung3b.php , without the separate graphic generation and lo and behold: now it works with HTML. The HTML header with <meta charset="utf-8"> is therefore mandatory.

Now I'm going to start troubleshooting the FPDF version, for which it must also be a charset problem.
Thanks a lot for your support!

**Comment by sprain** [comment]
The output I get from `rechnung3a.php` is this:

```
Fatal error: Uncaught Sprain\SwissQrBill\Exception\InvalidQrBillDataException: The provided data is not valid to generate a qr code. Use getViolations() to find details. in 
/home/www/vhosts/feiertagskalender.ch/github.feiertagskalender.ch/swiss_qr_bill/src/QrBill.php:194 Stack trace: #0 
/home/www/vhosts/feiertagskalender.ch/github.feiertagskalender.ch/swiss_qr_bill/src/PaymentPart/Output/AbstractOutput.php(174): Sprain\SwissQrBill\QrBill->getQrCode() #1 
/home/www/vhosts/feiertagskalender.ch/github.feiertagskalender.ch/swiss_qr_bill/src/PaymentPart/Output/HtmlOutput/HtmlOutput.php(40): Sprain\SwissQrBill\PaymentPart\Output\AbstractOutput->getQrCode() #2 
/home/www/vhosts/feiertagskalender.ch/github.feiertagskalender.ch/swiss_qr_bill/src/PaymentPart/Output/HtmlOutput/HtmlOutput.php(24): Sprain\SwissQrBill\PaymentPart\Output\HtmlOutput\HtmlOutput->addSwissQrCodeImage('<style>\n#qr-bil...') #3 
/home/www/vhosts/feiertagskalender.ch/httpdocs/pdf_rechnung3a.php(130): Sprain\SwissQrBill\PaymentPart\Output\HtmlOutput\HtmlOutput->ge in 
/home/www/vhosts/feiertagskalender.ch/github.feiertagskalender.ch/swiss_qr_bill/src/QrBill.php on line 194
```

The error message `The provided data is not valid to generate a qr code` has nothing to do with the html header. The origin of the problem must be somewhere else. Also, there really is no visible violations output :)

Maybe if you provide some more information, I can help. Feel free to re-open this issue.
