### ISSUE TITLE
Hillfe Bei der Installation..

### ISSUE THREAD

**Issue by iloveratte** [sprain/php-swiss-qr-bill#112]
Hallo zusammen.

Ich möchte gerne neben den offiziellen Orangenen Einzahlungsscheinen neu auf das QR System umsteigen (optional anbieten). Ich habe nun die Lib runtergeladen und auf den Server geladen, allerdings weiss ich nun nicht weiter. Wie generiere ich nun einen "Code" effektiv müsste dieser dann in ein PDF integriert werden (fpdf)..

aktuell wenn ich ein "example.php" aufrufe, erscheint: 
Fatal error: require() [function.require.php]: Failed opening required '/home/stephan/www/xyz.ch/libs/qr-rechnung/example/../vendor/autoload.php' (include_path='.:/usr/local/share/pear') in /home/stephan/www/xyz.ch/libs/qr-rechnung/example/example.php on line 5

von "autoload.php" finde ich aber in der Version die ich gedownloadet habe hier auf Github nichts..

Danke

**Comment by sprain** [comment]
Hallo @iloveratte – Die Library muss [via Composer](https://getcomposer.org) installiert werden. Eine deutschsprachige Info gibts hier: https://php-de.github.io/jumpto/composer/

**Comment by iloveratte** [comment]
Hallo. 

 

Das hilft mir gerade nicht weiter. Also wenn ich das nun verstehe, nur „Hochladen“ reicht nicht..?

 

Einfach sonnst einen „QR“ code generieren geht auch nicht?

 

Stephan

 

 

 

Von: Manuel Reinhard [mailto:notifications@github.com] 
Gesendet: Dienstag, 16. Februar 2021 14:22
An: sprain/php-swiss-qr-bill <php-swiss-qr-bill@noreply.github.com>
Cc: iloveratte <info@stephan-roos.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [sprain/php-swiss-qr-bill] Hillfe Bei der Installation.. (#112)

 

Hallo @iloveratte <https://github.com/iloveratte>  – Die Library muss via Composer <https://getcomposer.org>  installiert werden. Eine deutschsprachige Einführung gibts hier: https://php-de.github.io/jumpto/composer/

**Comment by sprain** [comment]
> Also wenn ich das nun verstehe, nur „Hochladen“ reicht nicht..?

Wenn du nur hochlädst, musst du dich selbst darum kümmern, die richtigen Files zu includen.

Es lohnt sich, sich mit Composer auseinanderzusetzen. Die PHP-Welt setzt seit bald 10 Jahren darauf, um externen Code auf praktische Weise in eigene Projekte zu integrieren. Hast du den Einstieg geschafft, wirst du begeistert sein.

**Comment by iloveratte** [comment]
Hallo. von begeistert bin ich noch weit entfernt, am Liebsten wäre mir Ohne Composer. gibt es da eine anleitung wie ich welche files brauche? denn im Download Ordner ist die "vendor/autoload.php" nicht enthalten. die ich überall einbinden muss. Warum muss man alles imme rnur kompliziert machen?

**Comment by sprain** [comment]
Ich bin einverstanden, dass der Einstieg in Composer nicht ganz einfach ist.

Kurzversion:
1. [Installiere Composer](https://getcomposer.org/doc/00-intro.md#installation-linux-unix-macos)
2. Wechsle ins Verzeichnis, wo du dein Projekt anlegen willst.
3. Lass den Befehl `composer require sprain/swiss-qr-bill` laufen – in diesem Moment wird diese Library und all ihre nowtendigen Abhängigkeiten heruntergeladen und (unter anderem) die Datei `vendor/autoload.php` wird erstellt.
4. Hol dir weitere Abhängigkeiten, die dein Projekt braucht – z.B. `composer require fpdf/fpdf`

Weitereführend hilft vielleicht diese Anleitung:
https://wiki.selfhtml.org/wiki/PHP/Tutorials/Abhängigkeiten_mit_Composer_verwalten

**Comment by iloveratte** [comment]
hallo. ja das habe ich beides bereits getan..

**Comment by sprain** [comment]
> hallo. ja das habe ich beides bereits getan..

Dann bist du auf bestem Weg. Wenn du dem `example.php` folgst, solltest dzu zim Ziel kommen.

Für weitere Hilfe ist hier aber der falsche Platz, da es nicht mehr um diese Library geht sondern generell um die Handhabung von Abhängigkeiten, Namespaces, etc.. Du kannst weitere konkrete Fragen dazu z.B. auf http://stackoverflow.com stellen oder dort auch schon Antworten finden. Viel Erfolg!

**Comment by iloveratte** [comment]
Hallo. ja genau das ist das Problem. bin seit tagen dran am laufen zu bringen, auch die Exemple Dateien laufen nicht, ebenfalls mit dem Hosting anbieter kontakt. und nun noch einen Monat zeit. es ist eifach eine Katastrophe.

**Comment by sprain** [comment]
So wie ichs einschätze, brauchst du etwas Hilfe bei ein paar Grundlagen der modernen PHP-Entwicklung. Wenn es dir möglich ist, würde ich dir empfehlen, dass du dir 2-3 Stunden Unterstützung bei einer Webagentur in deiner Nähe einkaufst. Wenn sich ein Entwickler dort Zeit nimmt, mit dir deinen Code durchzugehen und ein paar weiterführende Grundlagen zu erklären, wirst du weiterkommen.

An dieser Stelle hier sind die Möglichkeiten leider wirklich ausgeschöpft.
