### ISSUE TITLE
Leider habe ich keinen Erfolg

### ISSUE THREAD

**Issue by schweizerindeutsch** [sprain/php-swiss-qr-bill#113]
Der Betreff ist mittlerweilen irreführend, da ich nun zum Erfolg gekommen bin.
Ich bekomme das png was genau das ist was ich will, perfekt!
Gibt es auch einen möglichkeit die Rechung mit Empfänger und Sender und Betrag ohne Referenznummer zu erstellen.
in der minimalen Version ist leider der Sender nicht vorhanden.

**Comment by sprain** [comment]
> Gibt es auch einen möglichkeit die Rechung mit Empfänger und Sender und Betrag ohne Referenznummer zu erstellen.
in der minimalen Version ist leider der Sender nicht vorhanden.

Du kannst du benötigten Elemente beliebig zusammenstellen in deinem Code. Vorlagen findest du in `example.php` und `example_minimal.php`
