### ISSUE TITLE
Street number with lower case letter in createWithStreet

### ISSUE THREAD

**Issue by rgendroz** [sprain/php-swiss-qr-bill#117]
It seems the street number containg a lower case letter parsing with Postfinance goesn't in the right field. 
![image](https://user-images.githubusercontent.com/49240897/112151619-bbd2f800-8be1-11eb-9c90-056bfceefad4.png)

Example with 12B goes well

![image](https://user-images.githubusercontent.com/49240897/112152299-6f3bec80-8be2-11eb-8ad8-81d11a702c9c.png)

but the same example with 12b is not ok

![image](https://user-images.githubusercontent.com/49240897/112152380-867ada00-8be2-11eb-908d-98716be3f792.png)

thanks, with regards ;-)

**Comment by sprain** [comment]
Thanks!

Can you maybe provided the qr codes for those two examples? Then we can check whether this is an issue within this library or a bug over at Postfinance.

**Comment by rgendroz** [comment]
I'm so sorry, 
seems to be a cache problem in my local app...  ;-)
it goes well!

**Comment by sprain** [comment]
🙌 … this is the kind of bugs I enjoy 😄

**Comment by rgendroz** [comment]
A lot of bugs comes from between the end of the mouse and the keyboard, between the chair and the screen 😉😂
