### ISSUE TITLE
PDF generation using FpdfOutput.php fails

### ISSUE THREAD

**Issue by rsteimen** [sprain/php-swiss-qr-bill#123]
Following exception is raised
**Fatal error:** Uncaught Exception: FPDF error: Not a PNG file: data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIj8+CjxzdmcgeG1sbnM....

Reason:
In AbstractOutput.php $qrCodeImageFormat is private. In FpdfOutput.setQrCodeImageFormat "$this->qrCodeImageFormat" is used to set format. Due private scope qrCodeImageFormat is set on derived instance instead of base class.

Suggested fix:
Change scope of $qrCodeImageFormat in AbstractOutput.php from private to protected.

**Comment by sprain** [comment]
What version are you using? The issue you describe should be fixed in v2.13 and newer.
