### ISSUE TITLE
no images saved 

### ISSUE THREAD

**Issue by awberner** [sprain/php-swiss-qr-bill#128]
Hi, downloaded the library from composer and tried out the example.php. 
However no image are saved in the project, I think i'm missing something can you help me out ?
By the way, already checked the permissions of the folders and files of the project.

**Comment by sprain** [comment]
It very likely is not an issue of this library but of your local setup. But let's try if we find the reason.

What output do you get from the script if you replace the end of `example.php` (starting at line 78) with this?

```
try {
    $qrBill->getQrCode()->writeFile(__DIR__ . '/qr.png');
    $qrBill->getQrCode()->writeFile(__DIR__ . '/qr.svg');
} catch (Exception $e) {
	print $e->getMessage();
	exit;
}

print "done";
``

**Comment by awberner** [comment]
Your right ! It's looks like something's wrong with the local setup.
This is what I get with replacing the end code. 

```Unable to generate image: check your GD installation```

**Comment by sprain** [comment]
Good, now you know where to look into. GD is a very common php extension which is required to create images. You need to check your local php installation. Good luck!
