### ISSUE TITLE
Twint

### ISSUE THREAD

**Issue by vincenttarrit** [sprain/php-swiss-qr-bill#129]
Hello, how could I do to use this QR creator to make it works with TWINT ? Thank you !

---

**Answer:** (as found [in this comment](https://github.com/sprain/php-swiss-qr-bill/issues/129#issuecomment-1169607490))

It's possible to use the AlternativeScheme to make the QrCodes work with twint.
Something like this should work:

```
$qrBill->addAlternativeScheme(AlternativeScheme::create(
        'twint/light/<TWINT QrCode String>'
    ));
```
    
To get a TwintQR Code you need to be registered as a TWINT merchant.
See https://www.twint.ch/en/business-customers/our-solutions/bill-via-twint-qr-code/swiss-qr-code/?lang=en

**Comment by omueller** [comment]
@vincenttarrit  for me if I scan a QR code generated by the php-swiss-qr-bill library with Twint, I get "This swiss QR code is not yet compatible with Twint".      Will this ever be the case ?   I would guess no, as Twint will want to get 0.xxx% of the transaction.  

Maybe you will have more luck via https://www.twint.ch/en/business-customers/products/qr-code-sticker/ ? (you then need to register as a merchant, etc.).  

PS:  ok, it should be possible according to https://www.twint.ch/en/press/new-qr-bills-can-also-be-paid-using-twint/?lang=en, but you need to have a contract with Twint first.

**Comment by sprain** [comment]
In order for the QR bill to be paid with Twint, the corresponding `AlternativeScheme` must be integrated in the QR bill.

I have never actively tried to integrate Twint within one of my qr bills  and do not know whether it really is possible already. But there is some more information available here:

* https://www.paymentstandards.ch/en/home/software-partner/alternative-schemes.html
* https://twitter.com/TWINT_AG/status/1270709361065721856

**Comment by Julien0510** [comment]
Hello, does someone successfully make the qr works with TWINT ? Thanks

**Comment by raisenow** [comment]
My apologies, I didn't want to spam this with advertising but was trying to help. 
We do use this library. (And this approach works without being a RaiseNow customer. All you need is the TwintQr code). 

As you described above, it's possible to use the `AlternativeScheme` to make the QrCodes work with twint.
Something like this should work:

```
$qrBill->addAlternativeScheme(AlternativeScheme::create(
        'twint/light/<TWINT QrCode String>'
    ));
```

To get a TwintQR Code you need to be registered as a TWINT merchant. AFAIK this does not work for "Person to Person" payments.

**Comment by sdespont** [comment]
@raisenow the alternative scheme would only display the Twint QR-Code string. I don't really understand how it would help the customer to pay with his Twint app because it is not scannable.

**Comment by raisenow** [comment]
@sdespont no it will also change the QR-Code itself and then it is scannable with the Twint app.

**Comment by sdespont** [comment]
@raisenow OK, but then when using this new QR-Code, it is only payable with Twint? Or it would also be usable by banking apps?

**Comment by raisenow** [comment]
@sdespont both, twint and banking app

**Comment by sdespont** [comment]
@raisenow Oh, the alternative scheme is part of the QR-Code. Sorry, I missed that point...

**Comment by sprain** [comment]
> We do use this library.

👍😄

> As you described above, it's possible to use the AlternativeScheme to make the QrCodes work with twint. 
> To get a TwintQR Code you need to be registered as a TWINT merchant. AFAIK this does not work for "Person to Person" payments.

Thanks! This should be helpful for anybody wanting to integrate this functionality.

**Comment by sprain** [comment]
Twint handling is officially explained here:
https://www.twint.ch/en/business-customers/our-solutions/bill-via-twint-qr-code/swiss-qr-code/?lang=en

**Comment by h9k** [comment]
Sorry to bother on a closed issue, but it is totally unclear to me what the "Twint QRcode string" is and where to get it from exactly. I have an account at https://portal.twint.ch/ but I cannot find information anywhere. I only can generate so called QR code stickers with a fixed amount or free amount, but that does not appear to be very helpful.
Has anyone actually been successful at integrating Twint and wants to share what needs to be done Twint-side? Thank you!

**Comment by sprain** [comment]
The QR code stickers from Twint are something different than the QR bill. To create a QR bill which is payable by Twint you need a specific string to be added as an `AlternativeScheme` to the QR bill (see original post of this issue). You need to contact Twint to get this string.

**Comment by baerenklau** [comment]
Thank you very much for php-swiss-qr-bill, saved me a lot of time and trouble.
I stumbled over the Twint discussion and wanted to add the Twint possibility for the QR bill as well. I asked the Twint support a couple of times to for my QR-code-string. Either way it seems to be a very uncommon question or they are not happy to share the string or they do not share it at all. The last reaction was that they asked me to contact RaiseNow about the missing string/parameter. Can anyone verify that this would be an appropriate way or do I have to ask another question?

**Comment by sprain** [comment]
> If you are a billing party with medium-sized volumes (fewer than 10,000 bills per month) and would like to offer the TWINT QR code bill, please contact your billing party software provider directly. ([Source](https://www.twint.ch/en/business-customers/our-solutions/bill-via-twint-qr-code/swiss-qr-code/?lang=en))

Looks like Twint only wants to deal with merchants with more than 10'000 bills per month.

> The last reaction was that they asked me to contact RaiseNow about the missing string/parameter. Can anyone verify that this would be an appropriate way or do I have to ask another question?

You might have to ask RaiseNow about this. I suspect you are somehow connected to them, as a user or client?

**Comment by ucola** [comment]
hi @sprain same here, we became today an answer (after 2 month) that we need to contact RaisNow! Strange...

**Comment by sprain** [comment]
@raisenow Any ideas why Twint points people to you?

**Comment by raisenow** [comment]
Hey all, I'm happy to shed some light on the topic of Swiss QR codes
enriched with TWINT technology.

TWINT itself does not have a ready-to-go product for enriching Swiss QR
codes. Instead, they offer the base for technology providers/partners
with a certified TWINT direct integration to come up with a solution.
RaiseNow was the first provider in the market. And is still the only one as
of
today. There are certainly more providers to come.

The specific RaiseNow technology is very easy to get and set up. An
organization/company go and set up a RaiseNow account on
https://hub.raisenow.com/#/sign-up . After being approved by the KYC
process of RaiseNow (which usually takes 1 to 2 business days) you
can start enriching Swiss QR codes with TWINT-specific strings. The
step-by-step guide is available here:
EN:
https://support.raisenow.com/hc/en-us/articles/4405492590993-How-to-use-the-QR-payment-slip-TWINT-extension

DE:
https://support.raisenow.com/hc/de/articles/4405492590993-So-erweiterst-Du-den-QR-Einzahlungsschein-mit-TWINT
FR:
https://support.raisenow.com/hc/fr/articles/4405492590993-Bulletin-de-versement-QR-avec-TWINT

Depending on your price plan with RaiseNow the cost for this solution
varies.
For the simplest package, RaiseNow Free, you pay no setup fee, no monthly
fix fee, just a payment transaction fee of 2.5% in case of successful
payments.
The funds are paid out to the organization on a weekly base, 2.5% is
automatically deducted from the payout amount. For larger organization or
organization with high invoice amounts, please contact us.

If you want to test the solution you can go to https://qr-rechnung.net/#/ ,
they offer a TWINT enrichment process based on our solution.

Hope it helps.

Marco Zaugg
CEO of RaiseNow

**Comment by sprain** [comment]
Thanks for the clarification, @raisenow!
So in a nutshell, Twint does not want to add each merchant individually, but points to third-parties like RaiseNow.

**Comment by baerenklau** [comment]
I don´t get the whole logic about it but probably there is some. I can create a QR-code that lets someone make a payment to my Twint-Account if I use the App. Probably things like subject and amount could be added - maybe not. Does someone know whats the difference between a direct payment with Twint using the QR-code of the recipient and a QR-invoice link. What is the additional service of the payment service provider in this special case?

**Comment by sprain** [comment]
@baerenklau 

>  Does someone know whats the difference between a direct payment with Twint using the QR-code of the recipient and a QR-invoice link.

The Twint QR code is to be used with Twint only.
The QR invoice is mainly made to be used for bank transfers via your bank account. However, there is a feature which allows the QR invoice to be paid through other means, if they support it. Twint added this support and communicated it, but now does not really want to handle the work ;)

In my opinion, there are very few use cases where adding the Twint feature to the QR invoice make sense. It can be neglected for normal business cases.

**Comment by baerenklau** [comment]
Thanks a lot for your comment. So if I use Twint with e.g. Postfinance the QR-Code link with Twint would be more a link to the PSP Postfinance with potentially more payment options than Twint?
The case I thought would be nice is either a link to the Twint App with amount and subject or a QR code with the same information that allows a quick payment of an invoice (either PDF therefor the link or Paper with QR code). I think Twint is great for prepayment but would be also comfortable for invoice payment.

**Comment by sprain** [comment]
> So if I use Twint with e.g. Postfinance the QR-Code link with Twint would be more a link to the PSP Postfinance with potentially more payment options than Twint?

No. The qr invoice contains no link.
If the invoice supports Twint, the user still needs to decide in advance whether they want to use the app of their bank or the Twint app to scan and pay the qr invoice.

**Comment by baerenklau** [comment]
So probably a payment link that leads to the PSP payment site with a redirection to a
"thank you" page would be more customer friendly at all.
That is as far as I understand more or less the job that RaiseNow does.
Or alternatively the QR-code for the twint app which could be generated in the Twint user interface.
The only downside of this QR code is the missing amount and subject.

**Comment by raisenow** [comment]
Enriching a QR Bill format based on the Swiss QR Code standard with the
alternative payment option TWINT makes a lot of sense in a B2C context.
TWINT is the strongest digital payment option in Switzerland by now. More
than 5m users are registered. BUT, TWINT is a dedicated consumer app only.
Therefore,
adding TWINT as an alternative payment to an invoice which is sent to a
corporate recipient (B2B) doesn't make sense.

After scanning an enriched Swiss QR code with the TWINT app, you get
redirected to a payment page which shows the exact payment amount,
recipient data etc.
As an invoice sender aka merchant you can brand this payment page. The
feature is what @baerenklau is asking for. Technically, all information
that is encoded
in the Swiss QR code is read by the TWINT app and stored in your RaiseNow
transaction. Especially, and most importantly, the unique QR reference
numbers
which you need to automatically reconcile the payment against your
accounting subledger.

Adding a native TWINT QR next to a Swiss QR code is not recommended. People
get confused with two special QR codes formats that are both not readable
with
your normal QR codes scanner or mobile device camera app. In addition, the
risk of accidentally scanning the wrong qr code with the wrong app is high,
leading to
bad customer experience. That's why SIX invented the "alternative payment"
enrichment possibility in their Swiss QR code standard.

**Comment by sprain** [comment]
Thanks for all your ideas, opinions and comments.

For further discussion, let's focus on the technical aspects within this PHP library, as this is the purpose if this issue. The current state of things is summarized [in the original post above](https://github.com/sprain/php-swiss-qr-bill/issues/129#issue-908395414).
