### ISSUE TITLE
QR bill UTF8

### ISSUE THREAD

**Issue by onebeat** [sprain/php-swiss-qr-bill#130]
Hello, first i will like to thanks for this great script. 

We am building app for my client and there is issue with uft8 support, currently regarding extended latin letters .

Can this be solved or we are doing something wrong ?

**Comment by sprain** [comment]
If you are using `HtmlOutput`, your main html document might need to contain `<meta charset="utf-8"/>`.

Otherwise we might need to see some code to be able to help you. Feel free to re-open this issue with more information.

**Comment by onebeat** [comment]
Hello, i am using tcpdf as output option. Here is my code

`
$tcPdf = new TCPDF('P', 'mm', 'A4', true, 'UTF-8');
$tcPdf->setPrintHeader(false);
$tcPdf->setPrintFooter(false);
$tcPdf->AddPage();


$output = new QrBill\PaymentPart\Output\TcPdfOutput\TcPdfOutput($qrBill, 'en', $tcPdf);
$output
    ->setPrintable(false)
    ->getPaymentPart();


`
