### ISSUE TITLE
Country ISO Code for United Kingdom and Poland

### ISSUE THREAD

**Issue by pnussbaumer** [sprain/php-swiss-qr-bill#132]
Hello
I use php-swiss-qr-bill and I'm very happy with this product. But now I have a small problem with adresses in England or Poland. If I use the ISO-code for this contries "GB" or "PL" I receive an error-message "The value you selected is not a valid choice.".
What can I do for solving this problem?
It works fine with "DE" or "FR".

Best regards
Peter

**Comment by sprain** [comment]
Hi! I just tried `example.php` with country codes `PL` and `GB` and it worked as expected. 

I suppose the error message `The value you selected is not a valid choice` originates from outside this library. Please check where this error comes from. Then feel free to re-open this issue with more information and a code example.
