### ISSUE TITLE
Hi! I just tried `example.php` with country codes `PL` and `GB` and it worked as expected.

### ISSUE THREAD

**Issue by pnussbaumer** [sprain/php-swiss-qr-bill#134]
Hi! I just tried `example.php` with country codes `PL` and `GB` and it worked as expected. 

I suppose the error message `The value you selected is not a valid choice` originates from outside this library. Please check where this error comes from. Then feel free to re-open this issue with more information and a code example.

_Originally posted by @sprain in https://github.com/sprain/php-swiss-qr-bill/issues/132#issuecomment-856473198_

**Comment by sprain** [comment]
This by design. The qr bill only supports CHF and EUR.

See page 27 of the official specifications:
https://github.com/sprain/php-swiss-qr-bill/blob/master/docs/specs/ig-qr-bill-en-v2.1.pdf
