### ISSUE TITLE
CombinedAddress Payable to

### ISSUE THREAD

**Issue by onebeat** [sprain/php-swiss-qr-bill#135]
Hello, i have issue when i generete QRbill then my "test" city is only shown half on scan via bank app but on paper qrbill it shows everything without problem. I am using db data to show it on qr bill. When i put example data it works without problem. 

Can you help me with this issue ?

`$qrBill->setCreditor(QrBill\DataGroup\Element\CombinedAddress::create)`

**Comment by sprain** [comment]
Again, we will need to see an example and if possible also your code along with it.

**Comment by onebeat** [comment]
Here is code that i have inside QRbill generator

` $qrBill->setCreditor(
      QrBill\DataGroup\Element\CombinedAddress::create(
          $company_name,
          $company_address1,
          $company_address2,
          $company_address3
          /*'Robert Schneider AG',
          'Rue du Lac 1268',
          '2501 Biel',
          'CH'*/
      ));`

**Comment by sprain** [comment]
Unfortunately, this does not help much. Please provide

* a pdf of a qr bill which contains the error
* a code example how this pdf was generated

**Comment by sprain** [comment]
I will close this now as no feedback occured anymore. Feel free to re-open if you can provide more information.
