### ISSUE TITLE
Empty response without error messages on Windows server

### ISSUE THREAD

**Issue by kess78** [sprain/php-swiss-qr-bill#138]
Hi Sprain,
first of all, thank you very much for the software you provide us, it's simply awesome !

I'm facing a problem with your class on Windows Servers.
The situation: I install everything needed using composer and php7.3, on Windows and on Linux.
On Linux systems I'm able to use everything as expected, unfortunately not on Windows Systems.
If I test using your example.php, on Linux it generates the QR, on Windows nothing...

I have no logs, no errors, no nothing...

Do you perhaps have some hints ?
Thank you very much.

**Comment by sprain** [comment]
Hi @kess78 … I have absolutely no experience with windows servers and therefore no idea. I would try the following:

* Does php in general work on that machine? E.q. can you run a file containing `<?php phpinfo();`?
* Add debug output to example.php, like `die('Works until here');` and see where it fails.
* Add the following lines to the top of example.php and see if some errors appear now:

```
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
```

**Comment by kess78** [comment]
Hi @sprain,
thank you for your reply.

It works perfectly under Windows also, just had to enable ext-fileinfo.

Thank youvery much.
Bye Kess.
