### ISSUE TITLE
Bug: Issue generating QR Code from Iban for Postfinance

### ISSUE THREAD

**Issue by simplexx** [sprain/php-swiss-qr-bill#139]
There is a bug when generating a QR code from a postfinance IBAN. The error message is:
The payment reference type "QRR" does not match with the IBAN type of "POSTFINANCE_IBAN_HERE".
For testing, a regular, non QR-IBAN has been used. Now, when using the same  non QR-IBAN with the postfinance online QR code generator, it works just fine, so I assume this is either a bug or a compatibility issue in this library.

Postfinance qr code generator:
https://www.postfinance.ch/de/support/tools-rechner/qr-generator.html

**Comment by sprain** [comment]
Please provide the IBAN and a code example which causes the problem. Nothing bad can happen from it, besides that somebdy would send you some money 😄

**Comment by simplexx** [comment]
I have tested it with the account data from the url linked below (Sozialwerk Pfarrer Sieber) - same issue, so the data listed there data can be used to reproduce. Post QR code tool generates valid bill while the swiss qr bill lib throws the error mentioned above:
https://www.swsieber.ch/impressum/
https://www.postfinance.ch/de/support/tools-rechner/qr-generator.html

**Comment by simplexx** [comment]
The error is thrown at this line of code, when instead of a qr iban, the postfinance iban is used:
$output = new QrBill\PaymentPart\Output\HtmlOutput\HtmlOutput($this->qrBill, 'en');

the $this->qrBill object is created like this and then filled with all necessary data (everything works fine with the qr iban, but not with iban mentioned above)
$this->qrBill = QrBill\QrBill::create();

So I think to reproduce jist try to create any type of qr bill (html, pdf etc.) With the iban from above and you will see the issue.

**Comment by simplexx** [comment]
I see, thanks for the info and sorry for wasting your time.
