### ISSUE TITLE
Use of mime_content_type function()

### ISSUE THREAD

**Issue by Px-dev-fr** [sprain/php-swiss-qr-bill#140]
Hi ! I noticed that you where using the mime_content_type() function when you want to  get the payement part.  I have my file info activated but it's still not working. Any idea why ?

**Comment by sprain** [comment]
I am sorry, but I do not understand.

What exactly is the issue? If possible, please provide a code example and a description of what you expect to behave differently.

Feel free to reopen this issue with this additional information.

**Comment by Px-dev-fr** [comment]
Hi !

When I use this code:

`$output->setPrintable(false)->getPaymentPart();
`

my code crashes. I saw that it comes from when the code arrives at:

`if (!function_exists('mime_content_type')) {
            throw new MissingExtensionException('You need the ext-fileinfo extension to determine logo mime type');
        }`

Thanks for your help
