### ISSUE TITLE
Definition of StrdBkgInf changed in specifications v2.2

### ISSUE THREAD

**Issue by Beginner314** [sprain/php-swiss-qr-bill#142]
AlternativeScheme (field 33) is always sent, even though it is a empty array.

This triggers a note/warning in the postfinance validator: "The element 'AltPmt' may only be delivered if it is also filled."

**Comment by sprain** [comment]
Thanks for the report. Please provide a code example of when this happens.

**Comment by Beginner314** [comment]
Hi

It turnes out, that the Note on the postfiance testportal is kind of wrong.
The postfinance testportal gives following warning when **any** Element after "EPD" (Row 31) is sent but is empty.
![image](https://user-images.githubusercontent.com/15929376/133737222-bf3a1a47-6695-4f43-9540-008bd611938a.png)

Note: The Note says "Element 'AltPmt'" (Row 33) but it turnes out that in my case it is about Element "StrdBkgInf" (Row 32).

Reproduction:
`use Sprain\SwissQrBill as QrBill;

require_once(FRAMEWORK_DIR.'vendor/autoload.php');

$imagePath = CSF . '/tmp/qr_'.md5(microtime()).'.png';

// This is an example how to create a minimal qr bill:
// - no defined amount
// - no defined debtor
// - no reference number

// Create a new instance of QrBill, containing default headers with fixed values
$qrBill = QrBill\QrBill::create();

// Add creditor information
// Who will receive the payment and to which bank account?
$qrBill->setCreditor(
    QrBill\DataGroup\Element\CombinedAddress::create(
        'Robert Schneider AG',
        'Rue du Lac 1268',
        '2501 Biel',
        'CH'
    ));

$qrBill->setCreditorInformation(
    QrBill\DataGroup\Element\CreditorInformation::create(
        'CH9300762011623852957' // This is a classic iban. QR-IBANs will not be valid in this minmal setup.
    ));

// Add payment amount information
// The currency must be defined.
$qrBill->setPaymentAmountInformation(
    QrBill\DataGroup\Element\PaymentAmountInformation::create(
        'CHF'
    ));

// Add payment reference
// Explicitly define that no reference number will be used by setting TYPE_NON.
$qrBill->setPaymentReference(
    QrBill\DataGroup\Element\PaymentReference::create(
        QrBill\DataGroup\Element\PaymentReference::TYPE_NON
    ));

// Time to output something!
//
// Get the QR code image  …
try {
    $qrBill->getQrCode()->writeFile($imagePath);
} catch (Exception $e) {
    foreach($qrBill->getViolations() as $violation) {
        print $violation->getMessage()."\n";
    }
    print $e->getMessage();
    exit;
}`

This is the code from the "example-simple" of this library.
The problem is then "\n" at the end of QrBill.php => getQrCodeContent():
![image](https://user-images.githubusercontent.com/15929376/133737781-943471b0-76bb-40c5-8ac9-67e2220cb7c7.png)

This leads to a Row 32 (Element "StrdBkgInf") being sent but being empty.

The guidelines say that these two Elements ("StrdBkgInf" and "AltPmt") should only be send if they are not empty.
![image](https://user-images.githubusercontent.com/15929376/133737951-8ef44839-5a35-4fe7-9d47-4b57ddc6e9ea.png)
![image](https://user-images.githubusercontent.com/15929376/133738123-ac11af7e-1eb0-46f9-8a5c-390cb81f2517.png)

**Comment by sprain** [comment]
Thank you for the detailed report.

Interestingly, there are some precisions which were added in v2.2 of the specification (which I was not yet aware it existed).
https://www.paymentstandards.ch/dam/downloads/ig-qr-bill-en.pdf

Line 32 (`StrdBkgInf`) actually changed from `optional` to `additional`.

*v2.1*
<img width="1175" alt="Bildschirmfoto 2021-09-17 um 16 58 28" src="https://user-images.githubusercontent.com/260361/133804579-21a7db4a-f988-442f-8c95-60141687e796.png">

*v2.2*
<img width="1874" alt="Bildschirmfoto 2021-09-17 um 16 58 46" src="https://user-images.githubusercontent.com/260361/133804586-39dafbd0-9642-4280-8df7-7fcbf3200594.png">

So the library was correct, but the definition changed.

**Comment by Beginner314** [comment]
Ok, that's interesting.

I was in contact with postfinance and they said it's no big issue and should not interfer with any payment transactions.

**Comment by Beginner314** [comment]
@sprain Can you already

**Comment by sprain** [comment]
@Beginner314 
I provided an updated for this behaviour. If you want, you can give it a try with the according branch.
https://github.com/sprain/php-swiss-qr-bill/pull/146

I'll test myself and create a new release within the next few days.

**Comment by demianh** [comment]
I just stumbled upon this issue, as i tried to fix a Bug with our RaiseNow TWINT Integration.

What happens, if i want "Bill Information" to be empty, as shown in this example? https://support.raisenow.com/hc/en-us/articles/6463106978205-The-payload-of-a-QR-Bill

Currently, if i use this library and leave "Bill Information" empty (line 32), it just omits the line 32, which, according to the specs, is correct (empty lines are not allowed). But in this case, if i want to use "Alternative scheme parameters" on the lines 33/34, they move up to 32/33 because of the emitted line. But this is not valid, you can't just move these lines (Does not work with the TWINT App anymore). According to the standard, all the lines 32-34 are "Additional" = _"Must only be delivered if the element is not empty."_ 

I think this may even be a "logic"-problem of the spec. Does someone know, how to handle this case?

**Comment by demianh** [comment]
I just contacted SIX support (they manage the QR-Bill Standard), and they told me to use their [Validator](https://validation.iso-payments.ch/gp/qrrechnung/validation). Using the validator, i get the following Warning:

> Das Element <StrdBkgInf> darf nicht leer sein, wenn dieses geliefert wird. Ausnahme: Wenn nachfolgende Elemente verwendet werden. 

English: _The <StrdBkgInf> element must not be empty if this is supplied. Exception: If the following elements are used._ 

This means, we should update the library, to allow an empty line 32, if line 33 ist set. But only then.

**Comment by sprain** [comment]
@demianh Could you provide an example that triggers the error in the validator? Because interestingly, this qr code passed the validation the last time I did it:

* https://github.com/sprain/php-swiss-qr-bill/blob/master/tests/TestData/QrCodes/qr-alternative-schemes.txt
* https://github.com/sprain/php-swiss-qr-bill/blob/master/tests/TestData/QrCodes/qr-alternative-schemes.png
* https://github.com/sprain/php-swiss-qr-bill/blob/master/tests/TestData/QrCodes/proof-of-validation.png

**Comment by demianh** [comment]
Sure, here are the payload differences between 3.1.1 and later versions (only line 32 is different): https://gist.github.com/demianh/e6b70816ad5825c409b6ef5da3bb0529
Only the file from version 3.1.1 works with twint.

Interestingly, the exact same file i uploaded to the Validator yesterday, does not produce a warning today (even when i download and reupload it). Maybe they changed something, after i reported it? 
Currently, the validator is valid for both files. But only one works with the TWINT App.

**Comment by sprain** [comment]
@demianh 
You are welcome to test whether this PR fixes the issue for you:
https://github.com/sprain/php-swiss-qr-bill/pull/240

**Comment by sprain** [comment]
By the way, I am now getting this note in the validator:
![Bildschirmfoto 2023-11-09 um 10 26 18](https://github.com/sprain/php-swiss-qr-bill/assets/260361/03ae70cd-704f-43d0-a9a8-207ec5339a75)

I would appreciate it if you could show us the validator results of your two examples from above.

However, there are also some unexpected validation errors. I am not sure yet whether this is a bug in the validator. Also see #241
