### ISSUE TITLE
How to generate multiple QR facture on same page ?

### ISSUE THREAD

**Issue by pmaubertel** [sprain/php-swiss-qr-bill#147]
Hello,
I have installed your library and it works ok using the FPDF output.
Right now, it generates a PDF document with one QR facture at the bottom of each page.

However, I'm looking for a way to generate 3 QR factures at different vertical position
on the same page. I have tried the yoffset parameter but it moves only the images
and not the surrounding informations.
Is there a way to achieve this ?

Sincerely,

PM

**Comment by sprain** [comment]
Adding multiple qr invoices on one page with `FpdfOutput` is not actively supported by this library.

I suggest you use `HtmlOutput` which gives you much more flexibility in positioning and putting together an individual layout. If you need a pdf document in the end, a service like DocRaptor.com can be helpful.
