### ISSUE TITLE
Blank page on example.php

### ISSUE THREAD

**Issue by pelloq1** [sprain/php-swiss-qr-bill#148]
Hello,

I dont want to polluate this place with basics questions... 

But I think I dont done any mistake, and it wont work.

I installed the library on my local server where I develop my php app to integrate it on the invoice generation.

But before this I want to play with the samples, I get a blank page (the code is parsed becuase I can post some echo "test"; into, and the appears.

If I test the example/HtmlOutput/html-example.php I only get this : "HTML example created here: /volume1/web/xxx-app/example/HtmlOutput/html-example2.htm" 

Any help is welcome. 

Cédric 
from Wallis / Valais

**Comment by sprain** [comment]
> Is there a way to plot the result on a webpage without creating any file? Just draw the result on the current page?

In `example.php`, instead of saving the contents to a file you could do a `print $html;`.
