### ISSUE TITLE
6.1 Checking of field contents - validation of permitted combinations

### ISSUE THREAD

**Issue by ningappa** [sprain/php-swiss-qr-bill#15]
@sprain Nice meeting you

A validation is required. 

According to Swiss payment standards 2018, permitted combination of account and reference type should be validated. ( 6.1 - page 36 )

**Comment by sprain** [comment]
Thanks for your feedback!
Do you have an example where the library behaves wrongly? IMO those checks are implemented in https://github.com/sprain/php-swiss-qr-bill/blob/master/src/DataGroup/Element/PaymentReference.php#L86 and also covered with tests. But maybe I misunderstand.

**Comment by ningappa** [comment]
You may need to add type of account in CreditorInformation. Account types are IBAN or QR-IBAN. Depending on account type PaymentReference type should be auto selected. 
```
Account Type   | Reference type
===================================
IBAN           | SOCR ( TYPE_SCOR ) or NON ( TYPE_NON )
QR-IBAN        | QRR( TYPE_QR )

```
This kind of validation  i'm referring to.

**Comment by sprain** [comment]
You are welcome to check this out: #18
