### ISSUE TITLE
How to execute example.php to see the functionality of library

### ISSUE THREAD

**Issue by usmankhanfast** [sprain/php-swiss-qr-bill#152]
Hi,

I am new to this library and want to test its functionality in order to use it. How can I execute the example.php to get the swiss invoice.

Currently, I executed this command composer require sprain/swiss-qr-bill and executed 
localhost/ren/vendor/sprain/swiss-qr-bill/example/example.php but failed.

I then copied example.php to root folder and executed with below error

Uncaught Error: Class 'SimpleXMLElement' not found in /var/www/html/swiss/vendor/endroid/qr-code/src/Writer/SvgWriter.php:32\nStack trace:\n#0 /var/www/html/reno/vendor/endroid/qr-code/src/Writer/AbstractWriter.php(77): Endroid\\QrCode\\Writer\\SvgWriter->writeString()\n#1 /var/www/html/reno/vendor/endroid/qr-code/src/QrCode.php(412): Endroid\\QrCode\\Writer\\AbstractWriter->writeFile()\n#2 /var/www/html/reno/vendor/sprain/swiss-qr-bill/src/QrCode/QrCode.php(28): Endroid\\QrCode\\QrCode->writeFile()\n#3 /var/www/html/reno/example.php(80): Sprain\\SwissQrBill\\QrCode\\QrCode->writeFile()\n#4 {main}\n  thrown in /var/www/html/reno/vendor/endroid/qr-code/src/Writer/SvgWriter.php on line 32

**Comment by sprain** [comment]
> Uncaught Error: Class 'SimpleXMLElement' not found

It looks like your php installation is missing the `simplexml` extension.

How to fix this depends heavily on where you are running php, how you installed it and whether you are able to make changes there yourself. Please refer to the according documentation or partner for this.

**Comment by usmankhanfast** [comment]
When I execute example.php now qr. png and qr.svg are not found and execution halts. Can you please help?
