### ISSUE TITLE
generate full bill with all the text as PNG  (like html/pdf do)?

### ISSUE THREAD

**Issue by nikita65** [sprain/php-swiss-qr-bill#153]
First of all: great job Sprain!

I could not find out if it's already possible to generate as output a PNG image file that contains all the textual info. (like the one posted on your main github-project-page).

If not, would it be possible to add this feature?
Or, maybe, somebody can suggest a workaround (like going from html to png / pdf -> png)?

Thank you,
nIc

**Comment by sprain** [comment]
The image in the README of this library is simply a screenshot of a PDF file. Generating pngs for the whole payment slip is not supported by this libary (and also not recommended in general).

Google reveals some approaches to turn PDFs into PNGs with PHP. Yet I have no experience wih that.
