### ISSUE TITLE
How to output the PNG Image directly to the Browser?

### ISSUE THREAD

**Issue by dms-ts** [sprain/php-swiss-qr-bill#155]
Hi your example works fine, but I need to get the Result as PNG Image for direct download after processing.
There's no method getting the result as PNG without saving the File.

If get no result if I try something like this:
     print_r $qrBill->getQrCode()->writeDataUri();
Instead of:
    // $qrBill->getQrCode()->writeFile(__DIR__ . '/qr.png');

even if I get an result here, I still have to convert the dataurl into an image.

sorry am not a php developer

**Comment by sprain** [comment]
>  I still have to convert the dataurl into an image.

You either need to save the dataurl to a file or you can use it as a src in an html tag like this:

```html
<img src="data:image/png;base64,iVBORw0KGgoAAAANSU …">
```

**Comment by dms-ts** [comment]
Unfortunately, the data url only returns an empty string for me and I don't want to save the image, but would like only the temporarily generated PNG as result. Like this:


```
<?php
$im = imagecreatefrompng("test.png");

header('Content-Type: image/png');

imagepng($im);
imagedestroy($im);
?>
```

**Comment by sprain** [comment]
> Unfortunately, the data url only returns an empty string for me

This means something goes wrong earlier. If you post your full code, maybe we can help.
