### ISSUE TITLE
Support for both php7.4 and php8

### ISSUE THREAD

**Issue by prasidhda** [sprain/php-swiss-qr-bill#160]
Hi, 
Thanks for this great library. We are using this library to develop a simple WordPress plugin. 

Its great that this library supports php8 now, However I noticed from version 3.3, this library has dropped support for php7.4. 
Is It possible to add support for both php7.4 and php8? Will it be added in future releases? 

Any help would be greatly appreciated.

**Comment by sdespont** [comment]
I agree because security fixes are supported for PHP7.4 since november 2022. It is still safe to use it and people are migrating to 8 during this period. If an important fix must be provided for this library, only people already using PHP8 will be able to have it.

**Comment by sprain** [comment]
v3.2 works perfectly fine for PHP 7.4 and you can use this version. If an important fix is needed, a v3.2.1 could still be released.

Everything after v3.2 is for people who want to move to newer versions (e.q. Symfony 6 dependency does not support PHP 7.4 anymore either).
