### ISSUE TITLE
Output in version 2.19/3.2 is smaller then in 2.8

### ISSUE THREAD

**Issue by rebruCH** [sprain/php-swiss-qr-bill#162]
Need a little help if it would be possible. I have the problem that since rewriting the service for Symfony 5.x the QR Bill part is no longer the same size, although it is implemented 1:1 the same as in Symfony 3.x.

Old application all coherent (Version 2.8)
![image](https://user-images.githubusercontent.com/13044833/150790625-c9d40425-7bd8-4b57-af5d-bd93f2d02b11.png)

New application he is smaller (Version 3.2)
![image](https://user-images.githubusercontent.com/13044833/150791240-ee43c207-83ff-40e1-ba46-f6904d05a46a.png)

Have then also tried whether it is due to the version, have then installed 2.19, unfortunately with the same result, he scales it down.

Also tried to change something via the PDF Settings (go via KnpSnappy with Wkhtmltopdf) - but no matter if I set page-size, page-width, page-heigth or not, it still scales it down.

I'm slowly spinning my wheels and would appreciate a tip on what else this could be.

**Comment by sprain** [comment]
Which PaymentPart output are you using (Html, Fpdf or TcPdf)?
Can you provide some code to reproduce the issue?

**Comment by rebruCH** [comment]
Output is HTML

Code to reproduce (im knpsnappy which is using wkthmltopdf (0.12.6-r1) to generate the pdf)

```php
        $fileName = ($fileName===null) ? "QR-".$this->security->getUser()->getId().".pdf" : $fileName;
        $filePath = $this->parameterBag->get('cachepath').DIRECTORY_SEPARATOR.'qrcodes/';
        $file = $filePath.$fileName;

        $pdf = new Pdf($this->parameterBag->get('wkhtmltopdf'));
        $pdf->setOption('margin-left', 0);
        $pdf->setOption('margin-right', 0);
        $pdf->setOption('margin-top', 187);
        $pdf->setOption('margin-bottom', 0);

        if(!file_exists($filePath)) mkdir($filePath, 0777, true);

        if(file_exists($file)) unlink($file);
        $pdfFile = $pdf->generateFromHtml(utf8_decode($html), $file);

        return new \SplFileObject($file);
```

KnpSnappy is knplabs/knp-snappy-bundle v1.9

**Comment by sprain** [comment]
Ok, there is too much dependencies for a quick re-try.

* What if you compare just the HTML output without converting to a pdf. Is the bug already visible?
*  What if instead of using wkthmltopdf you paste the code [into the demo field here](https://docraptor.com/try_it_out) and generate a pdf. Is the problem visible?

This will help find out whether the problem stems from within the library or happens in wkhtmltopdf (which I suspect).

**Comment by rebruCH** [comment]
* HTML output compare
They are identical - only in the old version there is not only the \t there also \n in the generated html, which are missing in the new generated htmloutput

* Try it out PDF
Works - some small positioning problems, but the text is in normal size, not reduced like in the screenshots above.

This confuses me - because old and new implementation (Symfony side) using the same wkhtmltopdf (0.12.6-r1) but with different results. 

But anyway, i will rewrite the code to FPDF.

Thanks anyway! You can close the the issue.

**Comment by sprain** [comment]
I have always found `wkhtmltopdf` to be behaving a bit strange. So yeah, this library is definitely not taking care of its quirks. Good to know that switching to FPDF is a viable option for you 👍
