### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by peruf79** [sprain/php-swiss-qr-bill#166]
Hi

if I call fpdf-example.php I get the following error: "Class "SprainXX\SwissQrBills\PaymentPart\Output\FpdfOutput\FpdfOutput" not found". The example.php works fine and creates the png and svg. Thanks for your help, Peter

**Comment by sprain** [comment]
Looks like a typo on your side. The XX in the namespace is too much.

**Comment by peruf79** [comment]
Sorry, I entered the XX for testing purposes. But anyway, the full message is: "Fatal error: Uncaught Error: Class "Sprain\SwissQrBills\PaymentPart\Output\FpdfOutput\FpdfOutput" not found in D:\www\www387\php-swiss-qr-bill-master\example\FpdfOutput\fpdf-example.php:17 Stack trace: #0 {main} thrown in D:\www\www387\php-swiss-qr-bill-master\example\FpdfOutput\fpdf-example.php on line 17 "

**Comment by sprain** [comment]
SwissQrBills should be SwissQrBill.

**Comment by peruf79** [comment]
sorry, you are right: the s was the problem (I didn't read your answer complet). Now it works. Thanks for your help! How can I close this issue?
