### ISSUE TITLE
QR payment part without a predefined sum

### ISSUE THREAD

**Issue by PSchuetz** [sprain/php-swiss-qr-bill#169]
Is it possible to extend the script so that it could also be used without a fixed sum? 
Many associations have patrons or would like to generate donations and for this it should be possible to use the QR payment part without a predefined sum. Just as you can leave the debtor address open, I would like to be able to leave the sum open.

**Comment by sprain** [comment]
Of course!
https://github.com/sprain/php-swiss-qr-bill/blob/master/example/example_minimal.php
