### ISSUE TITLE
Swiss cross not showing in PDF

### ISSUE THREAD

**Issue by axelmy318** [sprain/php-swiss-qr-bill#171]
Hi, 

I'm using this library to output the invoice as HTML, and then import it to generate a PDF with it using file_get_contents(url)
I took the example of the HTMLOutput, and it works well when I go to the web page, but not when I import it using file_get_contents and passing it the webpage url.

Do you have a solution ?

**Comment by sprain** [comment]
Not all pdf creators handle svg files correctly.
Glad you found a solution that works for you!
