### ISSUE TITLE
Problems with missing classes or _construct

### ISSUE THREAD

**Issue by thekillerch** [sprain/php-swiss-qr-bill#173]
Hello,
I have always created a fpdf for our 'customers' and attached a pink payment paper. I would like to generate a QR bill instead at the bottom of the page.

Under composer (I never used it before) I see two lines: _fpdf/fpdf FPDF Composer Wrapper 1.84_ and _sprain/swiss-qr-bill A PHP library to create Swiss QR bills_

When I try to run the page I get Fatal error: Uncaught TypeError: Sprain\SwissQrBill\PaymentPart\Output\FpdfOutput\FpdfOutput::__construct(): Argument #3 ($fpdf) must be of type Fpdf\Fpdf, PDF given

I tried also replacing all what I have in the fpdf folder with the one Fpdf suggested in another issue but without luck.

In my code I have 
class PDF extends FPDF
      {
      ...
      }
$fpdf = new PDF('P','mm','A4');

If I change PDF to FPDF I get "there is already something with that name" error.     

I am really lost since it is the first time I use composer and I don't know what is connecting to what and when.

**Comment by sprain** [comment]
> class PDF extends FPDF

Since it‘s your first time using composer, make sure you use namespaces correctly, too. Maybe that‘s the problem here.

What‘s the fully qualified name of FPDF used in your PDF implementation? Is it `Fpdf\Fpdf`?

**Comment by sprain** [comment]
As there is no more feedback, I am closing this now. Feel free to re-open if there is new information on this issue.
