### ISSUE TITLE
How is the reference QR calculated? 

### ISSUE THREAD

**Issue by samayo** [sprain/php-swiss-qr-bill#174]
How do we calculate `Referenz`? It doesn't work not matter which library I used.

I always get "Invalid QR" and when uploading online it points to the references as being the issue. 

This is just a demo,

![image](https://user-images.githubusercontent.com/5304093/173641705-f53dc892-6cf9-43e3-9f5d-387141bf0a25.png)

**Comment by kohlerdominik** [comment]
With my Raiffeisen account the validator says, th IBAN is invalid. Should this be a valid IBAN?

**Comment by samayo** [comment]
> The QR reference may only be used with the so-called QR-IBAN, which is issued to customers by their bank.
The Creditor Reference (SCOR) has the same function as a QR reference. The difference is solely that the calculation thereof follows a different logic. Furthermore, it can be used in international payment traffic, while the QR reference is limited to Switzerland and Liechtenstein. A prerequisite for use of the SCOR is the concurrent use of the IBAN.

I still don't understand what this means. Can the reference number work with regular IBAN?

**Comment by kohlerdominik** [comment]
> > The QR reference may only be used with the so-called QR-IBAN, which is issued to customers by their bank.
> > The Creditor Reference (SCOR) has the same function as a QR reference. The difference is solely that the calculation thereof follows a different logic. Furthermore, it can be used in international payment traffic, while the QR reference is limited to Switzerland and Liechtenstein. A prerequisite for use of the SCOR is the concurrent use of the IBAN.
> 
> I still don't understand what this means. Can the reference number work with regular IBAN?

No, for QR reference you need to issue an QR-IBAN. This QR-IBAN is usually provided on request only.

But AFAIK you can use [RfCreditorReferenceGenerator ](https://github.com/sprain/php-swiss-qr-bill/blob/master/src/Reference/RfCreditorReferenceGenerator.php) with the regular IBAN, which might be what your looking for.

**Comment by samayo** [comment]
Thanks s lot
