### ISSUE TITLE
Unable to install a library via composer

### ISSUE THREAD

**Issue by zaietsv** [sprain/php-swiss-qr-bill#177]
Hello! 
I try to install a QR-Bill module using Composer dependencies. No one of below commands gives a positive result.

- composer require sprain/php-swiss-qr-bill:dev-master
- composer require -vvv -- sprain/php-swiss-qr-bill:4.1
- composer require -vvv -- sprain/php-swiss-qr-bill:4.1@dev

Each command downloads a list of stable tags and a "dev-master" but Composer unable to fetch a matching version. 
![image](https://user-images.githubusercontent.com/14337245/182708054-5f9f3cf3-db68-47ef-a3ee-8e574f5ea42a.png)

Finally a composer installation fails with a message:

  [InvalidArgumentException]                                                                                                                                                                         
  Could not find a matching version of package sprain/php-swiss-qr-bill. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (alpha). 

![image](https://user-images.githubusercontent.com/14337245/182707745-7bc449a8-30c4-4ee9-9035-e4fde058b3ae.png)

Please introduce a valid Composer versioning in order to provide a composer installation!

**Comment by sprain** [comment]
You are using the wrong package name.

`composer require sprain/swiss-qr-bill`

**Comment by zaietsv** [comment]
Wow. It works! Thank you!
