### ISSUE TITLE
Feature proposal: Add scissors symbol

### ISSUE THREAD

**Issue by JohnMag3** [sprain/php-swiss-qr-bill#180]
The scissors are missing on both seperation lines. The standard states that scissors must appear on both seperation lines. Please add the scissors, thank you!

`Personal Tip: Use the ✂ Font Symbol`

Reference: Style Guide QR-Bill (style-guide-en.pdf) -> Page 4 -> "Version 3 Qr-bill as PDF"

**Comment by sprain** [comment]
> Reference: Style Guide QR-Bill (style-guide-en.pdf) -> Page 4 -> "Version 3 Qr-bill as PDF"

Please also note the following paragraph on the same page::

```
«As an alternative to the scissors symbol, the note
"Separate before paying in" may be printed above the line.»
```

This is how it is currently done within this library.

> Please add the scissors, thank you!

This library is provided free of charge as open source software. Anybody can use it and everybody is welcome to contribute improvements in form of pull request. I would be happy to consider a pull request with this feature provided by … you, for example ;)
