### ISSUE TITLE
Resolve a conflict between QR-bill and Magento 2.4.4 two-Factor auth

### ISSUE THREAD

**Issue by zaietsv** [sprain/php-swiss-qr-bill#196]
Hello!
While upgrading Magento Community Edition to a version 2.4.4 there appears a conflict between a module SPRain QR-bill and a native Magento-2 module Two-factor Auth:

magento/module-two-factor-auth[1.1.3, 1.1.4] require endroid/qr-code ^4.3.5

sprain/swiss-qr-bill v3.3 requires endroid/qr-code ^3.9.7

![image](https://user-images.githubusercontent.com/14337245/193103358-1a35eab9-042e-4d59-b298-6244ac20d592.png)

Please kindly update a dependency “endroid/qr-code to a version ^4.3.5” in order to resolve a conflict with Magento-2!

A command is:

> /usr/bin/php8.1 /usr/bin/composer update -vvv

Hereby follows a full composer report:

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - magento/module-two-factor-auth[1.1.0, 1.1.1, 1.1.2] require php ~7.3.0||~7.4.0 -> your php version (8.1.10) does not satisfy that requirement.
>     - Root composer.json requires magento/product-community-edition 2.4.4 -> satisfiable by magento/product-community-edition[2.4.4].
>     - magento/security-package 1.1.3 requires magento/module-two-factor-auth 1.1.* -> satisfiable by magento/module-two-factor-auth[1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4].
>     - magento/module-two-factor-auth[1.1.3, 1.1.4] require endroid/qr-code ^4.3.5 -> satisfiable by endroid/qr-code[4.3.5, 4.4.0, 4.4.1, 4.4.2, 4.4.3, 4.4.4, 4.4.5, 4.4.6, 4.4.7, 4.4.8, 4.4.9, 4.5.0, 4.5.1, 4.5.2].
>     - You can only install one version of a package, so only one of these can be installed: endroid/qr-code[3.7.0, 3.7.1, 3.7.2, 3.7.3, 3.7.4, 3.7.5, 3.7.6, 3.7.7, 3.7.8, 3.7.9, 3.8.0, 3.8.1, 3.8.2, 3.9.0, 3.9.1, 3.9.2, 3.9.3, 3.9.4, 3.9.5, 3.9.6, 3.9.7, 4.3.5, 4.4.0, 4.4.1, 4.4.2, 4.4.3, 4.4.4, 4.4.5, 4.4.6, 4.4.7, 4.4.8, 4.4.9, 4.5.0, 4.5.1, 4.5.2].
>     - sprain/swiss-qr-bill v3.3 requires endroid/qr-code ^3.9.7 -> satisfiable by endroid/qr-code[3.9.7].
>     - magento/product-community-edition 2.4.4 requires magento/security-package 1.1.3 -> satisfiable by magento/security-package[1.1.3].
>     - Root composer.json requires sprain/swiss-qr-bill ^3.3 -> satisfiable by sprain/swiss-qr-bill[v3.3].
> 
> Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

**Comment by kohlerdominik** [comment]
Please update  to `"sprain/swiss-qr-bill" : "^4.3"`

**Comment by zaietsv** [comment]
Ah, that's fine! Let's try it out!
