### ISSUE TITLE
ISO 11649 support within the reference number

### ISSUE THREAD

**Issue by sdsys-ch** [sprain/php-swiss-qr-bill#197]
Hi,

according to Section 2.12 in [SIX - Swiss QR Bill Implementation Guide](https://www.paymentstandards.ch/dam/downloads/ig-qr-bill-en.pdf), Creditor Reference should also work but is currently not implemented, I believe.

Thanks for the great work!

**Comment by markus-ksg** [comment]
It is implemented and works fine, see example given in the first FAQ:
https://github.com/sprain/php-swiss-qr-bill/blob/master/example/example_scor.php:

```PHP
$qrBill->setPaymentReference(
    QrBill\DataGroup\Element\PaymentReference::create(
        QrBill\DataGroup\Element\PaymentReference::TYPE_SCOR,
        QrBill\Reference\RfCreditorReferenceGenerator::generate('I20200631')
    ));
```

**Comment by sdsys-ch** [comment]
Yes. My bad. I was under the wrong impression that the "creditor reference" could also be used with QR IBAN (vs SCOR with IBAN and CR).

Thanks for clarifying.
