### ISSUE TITLE
 Can't scan QR code with PostFinance App

### ISSUE THREAD

**Issue by gurtner-it** [sprain/php-swiss-qr-bill#198]
Hi,

I can't scan a QR Code with my Postfinance App using this code:

```
SPC
0200
1
CH4431999123000889012
K
GURTNER IT SOLUTIONS
Weststrassse 19
3005 Bern


CH







239.00
CHF
S
Beat Gurtner
Grosse Marktgasse
28
9400
Rorschach
CH
QRR
000000000000000000000202218

EPD
```

![qr](https://user-images.githubusercontent.com/52033286/193548050-e729043d-7b0f-4677-9cd0-4b8f1b35629d.png)

Any ideas?

PS I'm using the code from the example.php:

```
  // This is an example how to create a typical qr bill:
        // - with reference number
        // - with known debtor
        // - with specified amount
        // - with human-readable additional information
        // - using your QR-IBAN
        //
        // Likely the most common use-case in the business world.

        // Create a new instance of QrBill, containing default headers with fixed values
        $qrBill = QrBill\QrBill::create();

        // Add creditor information
        // Who will receive the payment and to which bank account?
        $qrBill->setCreditor(
            QrBill\DataGroup\Element\CombinedAddress::create(
                $Org->CompanyName,
                $Org->Street,
                $Org->zipCode.' '.$Org->city,
                'CH'
            ));

        $qrBill->setCreditorInformation(
            QrBill\DataGroup\Element\CreditorInformation::create(
                'CH4431999123000889012' // This is a special QR-IBAN. Classic IBANs will not be valid here.
            ));

        // Add debtor information
        // Who has to pay the invoice? This part is optional.
        //
        // Notice how you can use two different styles of addresses: CombinedAddress or StructuredAddress.
        // They are interchangeable for creditor as well as debtor.
        $res = $qrBill->setUltimateDebtor(
            QrBill\DataGroup\Element\StructuredAddress::createWithStreet(
                $patientName,
                'Grosse Marktgasse',
                '28',
                '9400',
                'Rorschach',
                'CH'
            ));

        // Add payment amount information
        // What amount is to be paid?
        $qrBill->setPaymentAmountInformation(
            QrBill\DataGroup\Element\PaymentAmountInformation::create(
                strtoupper($currency_code),
                $bil_final_amount
            ));

        // Add payment reference
        // This is what you will need to identify incoming payments.
        $referenceNumber = QrBill\Reference\QrPaymentReferenceGenerator::generate(
            Null,  // You receive this number from your bank (BESR-ID). Unless your bank is PostFinance, in that case use NULL.
            $Money->genBillNo($data['sal_date'], $bill_id, "") // A number to match the payment with your internal data, e.g. an invoice number
        );

        $qrBill->setPaymentReference(
            QrBill\DataGroup\Element\PaymentReference::create(
                QrBill\DataGroup\Element\PaymentReference::TYPE_QR,
                $referenceNumber
            ));


        // Now get the QR code image and save it as a file.
        try {
            unlink($GLOBALS['rootUrl'] . 'files/qr.png');
            $qrBill->getQrCode()->writeFile($GLOBALS['rootUrl'] . 'files/qr.png');
        } catch (Exception $e) {
          // foreach($qrBill->getViolations() as $violation) {
          //   print $violation->getMessage()."\n";
          // }
          // exit;
        }
```

PPS: Also use the orignal lines from examlpe.php is not helping

**Comment by sprain** [comment]
Hello @gurtner-it – I can scan this could and could execute the payment with may Raiffeisen app. I suggest you get in touch with PostFinance as it looks like this is an issue which is not related to this library.

**Comment by R3D2** [comment]
Same problem here... Did you find something that could explain why the QR is getting rejected by the app ?

**Comment by sprain** [comment]
@R3D2 
> I suggest you get in touch with PostFinance as it looks like this is an issue which is not related to this library.

**Comment by FredBoard** [comment]
I had the same issue... now solved.

If your .pdf contain more than **ONE** QR . ( for example, a second for a html link ), the PosteFinance Apps can't choice the right one...

Have you other QR on your file ?

**Comment by yannledev** [comment]
Hello, 

Same problem with Postfinance app + BCGE app.

in view of the responses in this thread, you're turning on the fact that the QR code is necessarily right and that the problem(s) automatically come(s) from the bank's scanning applications.

This may be the case, but how can you be sure? Rejecting a working hypothesis out of hand seems a bit short-sighted.

How do you debug a qr code and determine the cause of an "invalid qr code"?
After all, a qr code that can't be scanned is useless.

Thanks in advance

**Comment by sprain** [comment]
@yannledev 
Could you provide an example of such a QR code that cannot be scanned in your case? Then we can look into it.

**Comment by yannledev** [comment]
@sprain 

For my first attempt, I've just used the example code without modification of data/content qr data.
I've attached all the elements. (SVG generated, php code and result returned by a scan app)

![Capture d’écran 2024-03-17 à 09 55 27](https://github.com/sprain/php-swiss-qr-bill/assets/117514424/6b0f1d78-da58-44ca-b22d-13090b0aae0d)
[example-code.txt](https://github.com/sprain/php-swiss-qr-bill/files/14626806/example-code.txt)
[texte-D7420C239894-1.txt](https://github.com/sprain/php-swiss-qr-bill/files/14626807/texte-D7420C239894-1.txt)

**Comment by kohlerdominik** [comment]
Hello @yannledev

Can you scan this QR-code? It's made with the [Post QR generator](https://www.postfinance.ch/de/support/services/tools-rechner/qr-generator.html#/)
![grafik](https://github.com/sprain/php-swiss-qr-bill/assets/18621527/bc2efc7c-c29d-4a6a-9daf-796b9e0dae09)

This generator does not allow to use type `K` (combined) address-formats. It will enforce type `S` (structured) address. But beside of that the output looks exactly similar:
```
SPC
0200
1
CH4431999123000889012
S
Robert Schneider AG
Rue du Lac
1268
2501
Biel/Bienne
CH







2500.25
CHF
S
Pia-Maria Rutschmann-Schnyder
Grosse Marktgasse
28
9400
Rorschach
CH
QRR
210000000000000000694311650
Invoice 123456, Gardening work
EPD
```

---

My suggestion to narrow down the problem therefore is: Can you take the example code, but replace the `CombinedAddress` on [Line22 ](https://github.com/sprain/php-swiss-qr-bill)with this structured address (untestet):
```php
	QrBill\DataGroup\Element\StructuredAddress::createWithStreet(
		'Robert Schneider AG',
		'Rue du Lac',
		'1268',
		'2501',
		'Biel/Bienne',
		'CH'
	)
```

**Comment by kohlerdominik** [comment]
Addition to above: I rechecked the specs, because I thought, maybe it's an issue with the two empty lines in the `K` address. But I think the specs are pretty clear, and the implementation is correct here:
![grafik](https://github.com/sprain/php-swiss-qr-bill/assets/18621527/9ead55d2-062f-4f72-af06-8725ae822fa5)

**Comment by yannledev** [comment]
@kohlerdominik 
Thank you for your message.
I have tested to scan the qr code made with the Post QR generator and same result, error qr code invald.
But I make others tests with the Post QR generator and I confirm that type S (structured) address work now with the example.
Thanks for your help and the hint.
