### ISSUE TITLE
Always emit LI- prefix for Liechtenstein

### ISSUE THREAD

**Issue by markus-ksg** [sprain/php-swiss-qr-bill#199]
Follow-up to #188

The country code of Liechtenstein is indeed 'LI', but the code actually only produced the correct result **before** the PR #189 (by accident, because 'FL' is no valid country).

https://www.paymentstandards.ch/dam/downloads/ig-qr-bill-en.pdf says: "For invoicing to countries outside Switzerland, including Lichtenstein[sic!], the country code should be printed on the payment section."

I.e. the correct fix would have been to replace the whole
`in_array($this->getCountry(), ['CH', 'FL'])`
with
`$this->getCountry() === 'CH'

The `CombinedAddressTest` and `StructuredAddressTest` should also be fixed to expect `\nLI-9490 Vaduz`.

_Originally posted by @markus-ksg in https://github.com/sprain/php-swiss-qr-bill/issues/188#issuecomment-1260973656_

**Comment by sprain** [comment]
Fixed in v4.4 of this library 🙌
