### ISSUE TITLE
ParseError on PaymentReference.php Line Number: 117

### ISSUE THREAD

**Issue by pierre-debruyne** [sprain/php-swiss-qr-bill#203]
Hi ! 

I'm trying to make your package work on my project and i have an error on the setPaymentReference.
Here is the error : 

**Type**: ParseError
**Message**: syntax error, unexpected '|', expecting ';' or '{'
**Filename**: /vendor/sprain/swiss-qr-bill/src/DataGroup/Element/PaymentReference.php
**Line Number**: 117

I did exactly the same as you did on this exemple, just to see if it works :
https://github.com/sprain/php-swiss-qr-bill/blob/master/example/example_minimal.php

PHP Version 7.4.2

If someone have any idea ! 
Thanks !

**Comment by kohlerdominik** [comment]
PHP7.4 is not supported in the latest version. Can you try it with php8.0 or 8.1?

**Comment by pierre-debruyne** [comment]
Thanks for the quick reply ! I'll try on php8 ! 
Thanks
