### ISSUE TITLE
With XAMPP all is ok, online not

### ISSUE THREAD

**Issue by jobrat** [sprain/php-swiss-qr-bill#206]
Swiss Qr works very well on the local XAMPP Server, PHP 8.1.1, but when i upload the same files inkl. vendor there is no error message and no output. I put the memory_limit=512M, no effect. Online there is php 8.1 and also Apache.
Perhaps someone can help. Thank you!

**Comment by kohlerdominik** [comment]
Hi Jobrat

Probably Error Reporting is disabled?

Can you prefix your version in production with
```
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
```

Make sure, you don't do this in the live application!

**Comment by sprain** [comment]
Feel free to re-open this issue if you need help for a specific error message.

**Comment by jobrat** [comment]
Hallo Dominik

 

Vielen Dank für den Hinweis, hat aber leider nichts geändert.

 

 

 

Von: Dominik Kohler ***@***.***> 
Gesendet: Freitag, 4. November 2022 11:27
An: sprain/php-swiss-qr-bill ***@***.***>
Cc: jobrat ***@***.***>; Author ***@***.***>
Betreff: Re: [sprain/php-swiss-qr-bill] With XAMPP all is ok, online not (Issue #206)

 

Hi Jobrat

Probably Error Reporting is disabled?

Can you prefix your version in production with

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

Make sure, you don't do this in the live application!

**Comment by kohlerdominik** [comment]
If you can't produce an error message, we will not be able to help you. It might be better to reach out to the support of your hosting provider.
