### ISSUE TITLE
How can I exclude the text "Vor der Einzahlung abzutrennen"

### ISSUE THREAD

**Issue by pnussbaumer** [sprain/php-swiss-qr-bill#209]
I have new Forms for Printing and there exist the Text "Vor der Einzahlung abzutrennen" and so it does overprinting the text.

**Comment by kohlerdominik** [comment]
AFAIK it should be `->setPrintable(true)` on the output.

https://github.com/sprain/php-swiss-qr-bill/blob/f2628eaebc729de4b3ada71a130d8d90519f2105/example/HtmlOutput/html-example.php#L14

**Comment by pnussbaumer** [comment]
Many Thanks for this tip, it works fine.
