### ISSUE TITLE
allow_url_fopen check in fpdf

### ISSUE THREAD

**Issue by komunikelliot** [sprain/php-swiss-qr-bill#214]
In my environnement, the test in line 103 for the file src/PaymentPart/Output/FpdfOutput/FpdfOutput.php returned false, but the function were activated.

Original code that trigggered the error.
if ("1" === ini_get('allow_url_fopen')) {

Had to replace it with:
if( \filter_var( \ini_get('allow_url_fopen'), \FILTER_VALIDATE_BOOLEAN ) ) {
Now it works.

**Comment by kohlerdominik** [comment]
can you test this insted, please?
```php
if (TRUE === (bool) ini_get('allow_url_fopen'))
```

**Comment by sprain** [comment]
@kohlerdominik
It might be a good idea to adjust the test to check for a bool, as your example above does.

**Comment by komunikelliot** [comment]
It works like a charm also with this code

**Comment by komunikelliot** [comment]
It should be updated in next version.

**Comment by sprain** [comment]
Fixed in #216
