### ISSUE TITLE
Pdf rendering issues for AlternativeSchemes

### ISSUE THREAD

**Issue by rsteimen** [sprain/php-swiss-qr-bill#215]
Following issues were discovered as shown in the image while rendering alternative schemes in pdfs:
a) longer value is word-wrapped
b) text is in wrong size

A value for the alternative scheme is appended as followed:
`$qrBill->addAlternativeScheme(QrBill\DataGroup\Element\AlternativeScheme::create('CC/XRPL/10/rGqMTWrkWnb8ekVsZeNeS9t1pKBAAVDzSM'));`

Reason a)
In FpdfOutput.php, for `$this->setContentElement($furtherInformationElement, true)` true is passed instead of false (argument `bool $isReceiptPart`)

Reason b)
In FpdfOutput.php, `setTextElement` always sets `$this->fpdf->SetFont(...)` overriding previously set values in `addFurtherInformationContent()`.

![2023-02-20 16_18_27-QR-Zahlteil App 2023-02-20-11 pdf - Adobe Acrobat Reader (64-bit)](https://user-images.githubusercontent.com/58305632/220154003-f825ed76-d526-4ba7-98c6-8126f7cb2e93.png)

**Comment by sprain** [comment]
Thanks for reporting.
There is a fix ready in #228. You are welcome to test it, if you like.
