### ISSUE TITLE
Test Names with Long Characters Truncate Street Information in QR Bill Output

### ISSUE THREAD

**Issue by thomastpch** [sprain/php-swiss-qr-bill#223]
**Issue Description:**
Two different methods, createWithStreet() and CombinedAddress, were used to set the "Ultimate Debtor" information in QR bills with names approximately 40 characters long (with a maximum length of 61 characters). However, there was an issue where the street information was missing in the output under the "payable by" section.

Interestingly, on the right side of the QR bill, the full name and street are rendered correctly. This issue is not present when using the [PostFinance QR generator](https://www.postfinance.ch/en/support/services/tools-calculator/qr-generator.html#/).

**Steps to Reproduce:**
1. Run tests using names with long characters (approximately 40 characters) with a maximum length of 61 characters.
2. Use both `createWithStreet()` or `CombinedAddress` methods to set the "Ultimate Debtor" information in a QR bill.
3. Output in either HTML or PDF.
4. Observe that in the output, under the "payable by" section, the street information is missing.
5. Compare this behavior with the PostFinance QR generator, which does not exhibit this issue.

**Code Snippets:**
```php
$qrBill->setUltimateDebtor(
    QrBill\DataGroup\Element\StructuredAddress::createWithStreet(
        'Barnabé-Guy-Octave de Fleury-Mombreuse du Pantel de Saint-Ama',
        'Teststrasse',
        '9',
        '8600',
        'Dübendorf',
        'CH'
    )
);

$qrBill->setUltimateDebtor(
    QrBill\DataGroup\Element\CombinedAddress::create(
        'Barnabé-Guy-Octave de Fleury-Mombreuse du Pantel de Saint-Ama',
        'Teststrasse 9',
        '8600 Dübendorf',
        'CH'
    )
);
```

**Expected Behavior:**
The street information should be correctly displayed in the "payable by" section of the QR bill output when using both `createWithStreet()` and `CombinedAddress` methods, similar to how it is rendered on the right side of the QR bill.

**Actual Behavior:**
The street information is missing in the "payable by" section of the QR bill output when using both `createWithStreet()` and `CombinedAddress` methods.

![2023-09-15_120040](https://github.com/sprain/php-swiss-qr-bill/assets/74813096/4e17dbca-4d57-4bfd-9004-ed59844981ed)

**Comment by sprain** [comment]
Thanks for your nessage, @thomastpch 

The described behaviour is by design and was introduced in #190. It covers a situation that is not explicitly solved in the qr code specifications. See https://github.com/sprain/php-swiss-qr-bill/issues/187#issuecomment-1236196794 form more information on how the decision was made.
