### ISSUE TITLE
Methods in AbstractOutput should return static instead of self

### ISSUE THREAD

**Issue by gregor-tb** [sprain/php-swiss-qr-bill#224]
This code from the example let all external tools report "UndefinedMethod" (psalm, stan, phan)

```
$output = new QrBill\PaymentPart\Output\HtmlOutput\HtmlOutput($qrBill, 'en');
$output->setPrintable(false)->getPaymentPart();
```

setPrintable() (and some other methods in AbstractOutput) should be declared return static, not self. getPaymentPart() only exists on HtmlOutput.

**Comment by sprain** [comment]
Thanks for reporting.
Fixed in v4.8.2 of this library.
