### ISSUE TITLE
how many characters are allowed in additionalInformation?

### ISSUE THREAD

**Issue by heinz-jonen** [sprain/php-swiss-qr-bill#226]
I have an additional information in the QR invoice for a customer, but it contains about 100 characters. This does not work. Why?
Thanks for hints.
Heinz

**Comment by sprain** [comment]
It should support up to 140 characters.
https://github.com/sprain/php-swiss-qr-bill/blob/8660621c81165213c874de269ff7cce4a37a881b/src/DataGroup/Element/AdditionalInformation.php#L82C4-L82C4

> This does not work. 

We will need more specifics to be able to help :)

**Comment by heinz-jonen** [comment]
Hi Manuel
my english is not perfect, but I wanted to include the following text into AdditionalInformation:

Einrichtung von https und PHP 8.2 auf [www.noname-domain.ch](http://www.noname-domain.ch/)

and the result in the pdf is (see the screenshot).

Why does this happen?

Heinz
![Screenshot 2023-09-26 154838](https://github.com/sprain/php-swiss-qr-bill/assets/64215396/704eee78-f0ec-4ab4-955a-ab9c761817d2)

**Comment by sprain** [comment]
@heinz-jonen Which output of this library are you using? It looks like a line height issue there.

**Comment by heinz-jonen** [comment]
Hi Manuel
I send you the file I use as attachment
[rechnung_extern.zip](https://github.com/sprain/php-swiss-qr-bill/files/12737941/rechnung_extern.zip)
hope, you will find out what I have done wrong.
Heinz

**Comment by sprain** [comment]
@heinz-jonen
It looks like you build your own pdf file to create the qr bill. This is unfortunately out of scope of where we can provide support here.

I suggest you take a look at the existing `FpdfOutput` provided with this library:
https://github.com/sprain/php-swiss-qr-bill/blob/master/example/FpdfOutput/fpdf-example.php
