### ISSUE TITLE
Allow empty amount

### ISSUE THREAD

**Issue by ovesco** [sprain/php-swiss-qr-bill#23]
Hey thanks a lot for that library!
Reading the official documentation about QR bills, I found out that it's possible not to define any amount in the invoice (for example to allow debtor to pay a little more or round it).
But removing the given amount in the qr code results in a violation, is it normal?

Thanks!

**Comment by sprain** [comment]
Hello .. for some reason I missed your issue until now.

An empty amount is possible, but you still need to define a currency. So make sure you set ‘PaymentAmountInformation‘ with a null amount.

**Comment by ovesco** [comment]
Thanks for the clarification it works perfectly!
By the way I used it in a template I made with FPDF for the whole payment part, would you be interested?

**Comment by sprain** [comment]
> By the way I used it in a template I made with FPDF for the whole payment part, would you be interested?

Yes, I am interested :)
