### ISSUE TITLE
Debtor address with more than 3 lines

### ISSUE THREAD

**Issue by milkee-ch** [sprain/php-swiss-qr-bill#234]
I'm trying to generate a QR bill for a company that has six (yes, six) lines in her address.

It is structured as following:

1. Name of the company
2. Name of the subcompany
3. Name of the person
4. Name of the c/o 
5. Actual street
6. City / ZIP

The structured address as well as the combined address only allow up to 4 lines.

Is there any chance that I can get this done?

**Comment by sprain** [comment]
No chance, the official specification of the QR bill does not allow different address formats than the two provided in this library.

**Comment by milkee-ch** [comment]
That's a bummer, but thanks for your fast response!

**Comment by sprain** [comment]
Potential workaround: Leave the address empty and a placeholder will be shown on the qr bill. This is how we handle it in our company for non-standard addresses. I suppose you will put the legal invoice address somewhere else on the invoice anyway.

**Comment by milkee-ch** [comment]
Fair enough, that should work! Thanks for the help :)
