### ISSUE TITLE
#qr-bill h1 CSS is missing line-height reset

### ISSUE THREAD

**Issue by pivica** [sprain/php-swiss-qr-bill#237]
All other elements in CSS have line-height reset except `#qr-bill h1` element. Because of that h1 page CSS line-height rule will be applied which can produce unexpected result - like in my case h1 been pushed to bottom by some pixels and not aligned with top of the bill. 

For me adding `#qr-bill h1 { line-height: 1; }` rule was enough to fix this and it produces the same visual result like on qt bill example image on [php-swiss-qr-bill](https://github.com/sprain/php-swiss-qr-bill) github home page.

Not sure is `line-height: 1;` is enough or some more specif value should be used - I don't think h1 label will be long enough to break into multiple lines, but even in that case h1 element  with line-height 1 looks good (I've tested it in browser).

**Comment by sprain** [comment]
Thank you!
Could you maybe provide a screenshot that shows the problem you encountered?

**Comment by pivica** [comment]
Here you are, left screenshot is with `line-height: 1` active, right is when this rule is deactivated

|with a fix|without a fix|
|---|---|
|![ksnip_20231023-234635](https://github.com/sprain/php-swiss-qr-bill/assets/1798146/3993c092-ece0-4bc2-b8d0-0553812e58b6)|![ksnip_20231023-234631](https://github.com/sprain/php-swiss-qr-bill/assets/1798146/2625e48f-16b1-410c-b349-d02ba8d0b9ef)|

You can see how h1 get vertically shifted because of line height rule it is getting from page css.

**Comment by sprain** [comment]
@pivica Thank you!
You are welcome to test, whether this PR fixes the issue:
https://github.com/sprain/php-swiss-qr-bill/pull/238

**Comment by pivica** [comment]
Sorry for late reply, this change is fixing the problem we also had. Thanks for #238 change.
