### ISSUE TITLE
Receive random message "This value should not be blank"

### ISSUE THREAD

**Issue by prevessin** [sprain/php-swiss-qr-bill#243]
Receive random message twice "This value should not be blank" when attempting to create qr.svg / qr.png : '../sprain/swiss-qr-bill/example/FpdfOutput/qr.svg'

**Comment by sprain** [comment]
@prevessin I cannot reproduce this with the examples.
Which example exactly are you running? What output exactly do you get?

**Comment by apcpveya** [comment]
I had the same issue. My problem came from ultimateDebtor->postalCode was empty

I had to generate an invoice for an address in HonkKong, without postalCode
