### ISSUE TITLE
QrBill only on the first page

### ISSUE THREAD

**Issue by gmarineau** [sprain/php-swiss-qr-bill#246]
Hi,

First thank you for the package ! Great works.

I have juste one question, it's possible to keep the QrCode on the first page if we have more than one pages with TcPdf.

This how I implement the QrBill with TcPpdf
```
$qrBill = $this->generateQrBill($invoice);

if (is_null($pdf)) {
    $output = new HtmlOutput($qrBill, 'fr');
} else {
    $output = new TcPdfOutput($qrBill, 'fr', $pdf);
}

try {
    $output->setPrintable(false);

    return $output->getPaymentPart();
} catch (InvalidQrBillDataException $e) {
    foreach ($qrBill->getViolations() as $violation) {
        echo $violation->getMessage();
    }
}
```

**Comment by sprain** [comment]
> it's possible to keep the QrCode on the first page if we have more than one pages with TcPdf.

This is not a functionality directly provided by this library.
You might create two pdfs and then merge them somehow.
