### ISSUE TITLE
Receipt part with long address

### ISSUE THREAD

**Issue by sdespont** [sprain/php-swiss-qr-bill#248]
I can't find where the documentation explains that the receiving room can't have multiple lines.

Address like:

```
$qrBill->setCreditor(
    QrBill\DataGroup\Element\CombinedAddress::create(
        'Robert Schneider AG',
        'p.a. My long-company-name Sàrl, Av. de la Gare 66',
        '2501 Biel',
        'CH'
    )
);
```
is printed like this:

```
    Robert Schneider AG
    2501 Biel
```

![image](https://github.com/sprain/php-swiss-qr-bill/assets/646632/1a9846e7-de24-4ed1-b605-a140eb11ee68)

Because of 

https://github.com/sprain/php-swiss-qr-bill/blob/c5e69dd8d7becc994fd467eb2e7148bc56e1944b/src/DataGroup/Element/Abstracts/Address.php#L30

https://github.com/sprain/php-swiss-qr-bill/blob/c5e69dd8d7becc994fd467eb2e7148bc56e1944b/src/DataGroup/Element/StructuredAddress.php#L150-L152

Can you confirm that this is the desired behavior?

**Comment by kohlerdominik** [comment]
It's desired behaviour as because there were overlaps. It was discussed in #187 and this is probably a duplicate of #223.

**Comment by sdespont** [comment]
@kohlerdominik ok, thanks for the quick answer
