### ISSUE TITLE
Multiple "This value should not be blank" are unclear

### ISSUE THREAD

**Issue by dkameleon** [sprain/php-swiss-qr-bill#257]
I set empty address/postcode/town then after calling 
```
        foreach ($qrBill->getViolations() as $violation) {
            print $violation->getMessage()."\n";
        }
```
I got multiple identical errors in a row:
```
This value should not be blank
This value should not be blank
```

I believe errors should be more clear and refer to exact fields.

**Comment by kohlerdominik** [comment]
I agree, that the example is not perfect for this. AFAIR you can use `$violation->getPropertyPath()` to get information on which field was invalid. I think it's just the default behaviour of [symfony/validator](https://symfony.com/doc/current/components/validator.html).
