### ISSUE TITLE
Tests for PHP 7.4 not working on Travis CI

### ISSUE THREAD

**Issue by sprain** [sprain/php-swiss-qr-bill#26]
There is a [branch for PHP 7.4 support](https://github.com/sprain/php-swiss-qr-bill/tree/php-7.4) already, but tests are not running yet on Travis CI due to a missing GD extension.

Error message from https://travis-ci.org/sprain/php-swiss-qr-bill/jobs/619641155:
```
endroid/qr-code 3.7.3 requires ext-gd * -> the requested PHP extension gd is missing from your system.
```

I am not yet sure whether we simply have to be patient for Travis CI to fix the issue or if there is something we can do about it.

Also see [this discussion](https://travis-ci.community/t/add-php-7-4-branch-to-test-against/2179/16?u=sprain) in Travis CI forums.

**Comment by sprain** [comment]
GD extension issue is fixed.

Now we need this pr to get merged in one of the dependencies:
https://github.com/khanamiryan/php-qrcode-detector-decoder/pull/78

**Comment by kohlerdominik** [comment]
Hi @sprain 

Looks like the required dependency is badly maintained. Is there any chance of switching to another qr-code package?

**Comment by sprain** [comment]
Sure. Any suggestions?

**Comment by kohlerdominik** [comment]
Well, you're probably better suited to investigate if the package supports the required functionality, but a quick research within packagist did lead me to 3 results:

- https://github.com/Bacon/BaconQrCode
the most obvious one, as it's a dependency of [endroid/qr-code](https://packagist.org/packages/endroid/qr-code), the currently used package

- https://github.com/tecnickcom/TCPDF
supports a lot of stuff, doesn't depend on any packages and has very wide compatibility (>=5.3.0). However, it might be very heavy for just a qr-code

- https://github.com/chillerlan/php-qrcode
seems very well maintained at the moment. php-compatibility might be an issue though, and i dislike that it doesn't follows PSR-12.

But from the compatiblity point of view, regarding at PHPs at [Supported Versions](https://www.php.net/supported-versions.php), i think php7.1 could be easily dropped, and probably even php7.2 with a new 3.0 release of this package.

**Comment by sdespont** [comment]
@kohlerdominik What do you mean by "badly maintened"? 

endroid/qr-code is existing since a long time and has regular updates and is used by a lot of others libraries.

**Comment by kohlerdominik** [comment]
@sdespont sorry for being unclear here. i meant https://github.com/khanamiryan/php-qrcode-detector-decoder, which is is a dependency of endroid/qr-code. So i didn't want to say endroid/qr-code is maintained badly, but the required dependency of khanamiryan/php-qrcode-detector-decoder could be a poor choice.

As coincidence wants, [khanamiryan/php-qrcode-detector-decoder#78](https://github.com/khanamiryan/php-qrcode-detector-decoder/pull/78) got merged today after being open for nearly 8 months (!!!)

**Comment by sprain** [comment]
> As coincidence wants, khanamiryan/php-qrcode-detector-decoder#78 got merged today after being open for nearly 8 months (!!!)

I asked again, and now it was finally merged.

I created a pull request (#33). There is still one failing test and a number of deprecation notices. I'll have a look. Anybody who wants to help is welcome to do so.

**Comment by sprain** [comment]
@kohlerdominik Done! https://github.com/sprain/php-swiss-qr-bill/releases/tag/v2.5
