### ISSUE TITLE
QR Bill without Debitor

### ISSUE THREAD

**Issue by ncavallini** [sprain/php-swiss-qr-bill#261]
Hello, is it possible to create a QR Bill without debitor (but with creditor and amount) such that I can receive a payment even without knowing the address of the person that owe me money?

Thanks
Regards.
Niccolò Cavallini

**Comment by sprain** [comment]
Sure, the debtor is optional.
As an example, see here:
https://github.com/sprain/php-swiss-qr-bill/blob/master/example/example_minimal.php
