### ISSUE TITLE
Scissors wrongly positioned in HtmlOutput

### ISSUE THREAD

**Issue by sprain** [sprain/php-swiss-qr-bill#266]
Scissors positioning in `HtmlOutput` is not always as expected.

This needs further reproduction and digging into.

![Bildschirmfoto_2024-11-11_um_11_05_14](https://github.com/user-attachments/assets/8b6b655e-faed-4b0e-bbb7-d1469e50967a)

**Comment by kohlerdominik** [comment]
Probably should also inform @tafel here, so they can keep their eyes open.

**Comment by tafel** [comment]
Is this from the raw HTML in the browser, or after transforming it into a PDF? If it's a PDF, what is the translator html>pdf?

**Comment by sprain** [comment]
It's in a converted pdf, but already looks wrong in HTML.
I changed position behaviour in my PR and probably overlooked the case when the payment slip will be moved around on the page.

**Comment by tafel** [comment]
I saw you changed the position to `fixed`. It's probably what's causing the problem. 
Check this video

https://github.com/user-attachments/assets/19eea553-0c35-4fd1-9312-37fb859fbc45

Do you remember what was the reason for fixed position?

**Comment by sprain** [comment]
> Do you remember what was the reason for fixed position?

Yes, the previous positioning actually changed the size of the whole payment slip, making it higher by the size of the scissors.
