### ISSUE TITLE
invoice on multipage

### ISSUE THREAD

**Issue by chatis** [sprain/php-swiss-qr-bill#27]
I have created a file that have more than 1 invoice on it and also more than one page per invoice...

How can I put the QR block at the bottom of each page when I print the document ?

Please take a look to my code and try to print it.

This is impossible to have the QR box at the end of the page

[bvr.txt](https://github.com/sprain/php-swiss-qr-bill/files/4226694/bvr.txt)

[bvr.html.pdf](https://github.com/sprain/php-swiss-qr-bill/files/4227581/bvr.html.pdf)

**Comment by sprain** [comment]
You will likely have to deal with the css properties `page-break-after` as well as good use of relative / absolute positioning.

I am closing this as it is more of a support question than an issue with the library.
