### ISSUE TITLE
Provide a way to create full payment parts

### ISSUE THREAD

**Issue by sprain** [sprain/php-swiss-qr-bill#3]
Unclear yet how to do it. Until now, the library only creates the qr code image. Eventually it should be able to create the full payment part.

It would be great to provide a simple way to do it in FPDF, Twig, and any others that users would like to use.

See https://github.com/sprain/php-swiss-qr-bill/blob/master/doc/specs/ig-qr-bill-en-v0100.pdf page 11 and following and page 31 and following for visual examples.

**Comment by ovesco** [comment]
I created a full template in FPDF to fit my needs.
I think it would be for the best for the library to implement a way to choose between various "renderers" (FPDF, Twig...) and let the dev choose the one he wants

**Comment by sprain** [comment]
PR #22 is very close to being merged. It will add exactly this: support for multiple output formats. The PR currently supports `HtmlOutput`, but one could add an `FpdfOutput`.

See https://github.com/sprain/php-swiss-qr-bill/tree/html-output/src/PaymentPart/Output

So if you wish, you are welcome to contribute there – now or after it's officially released.
