### ISSUE TITLE
Errors with accentuated characters in translation.

### ISSUE THREAD

**Issue by Franco2911** [sprain/php-swiss-qr-bill#34]
There are strange spaces on the accented characters in the translation file.
You can have a look at the changes I made in the Pull Request #32  and add it to the new version 2.5.

Thank you for help.

**Comment by sprain** [comment]
> There are strange spaces on the accented characters in the translation file.

Do you see those spaces in the actual php file or only in your payment part output?
I am not yet able to reproduce this issue.

**Comment by Franco2911** [comment]
If you check in your translation file by selecting the accentuated characters you will see these spaces.
With utf8_decode function accented characters do not work then by rewriting the characters in the file it works fine.
Have a look in the file of the pool request you will see what I meen.

**Comment by Franco2911** [comment]
You are right, you cant see that in GitHub but if you select the accentuated characters in PHPStorm there are 3 parts it strange but if you copied the translation from a pdf it is a frequent bug.

**Comment by sprain** [comment]
> if you select the accentuated characters in PHPStorm there are 3 parts it strange

The thing is that it looks fine in my PHPStorm 🤔
I am not sure where to start looking as I actually have never had any encoding issues when working in PHPStorm.

**Comment by Franco2911** [comment]
What you can do is simply rewrite the word with an accent in your IDE and save it. It is what I did.
Before rewritting all accentuated letters was replaced by ? and after all worked fine.

**Comment by sprain** [comment]
Strange, but yeah … https://github.com/sprain/php-swiss-qr-bill/pull/38
