### ISSUE TITLE
add additional information

### ISSUE THREAD

**Issue by Tarom11** [sprain/php-swiss-qr-bill#45]
Good day

We would like to add additional information. 
In addition to the reference, the additional information should also be listed.
Unfortunately this is not possible, do you have an additional function here?

**Comment by sprain** [comment]
It's there. You can do it like this:

```
$additionalInformation = new AdditionalInformation::create('Your information text');
$qrBill->setAdditionalInformation($additionalInformation);
```

Feel free to re-open this task and add more information if this doesn't do what you want.
