### ISSUE TITLE
Bad utilization of the placeholders

### ISSUE THREAD

**Issue by sdespont** [sprain/php-swiss-qr-bill#47]
In the [specification](https://www.paymentstandards.ch/dam/downloads/drehbuch-rechnung-steller-empfaenger-en.pdf), there is only one case where the placeholders must be displayed : if there is no ultimate debtor, without amount and not using a QR-IBAN (therefore, no reference number neither).

In the current version, it is possible to set an amount as NULL to display the placeholders.

But, perhaps I am misunderstanding the documentation. Can you explain why you coded this feature this way?

**Comment by sprain** [comment]
> In the current version, it is possible to set an amount as NULL to display the placeholders.

I do not see an issue here. Consider the use case of a charity for example: I know your name, I know your user account where I will book your payment, but it's up to you how much you want to pay. In this case, debtor and reference number are know, but not the amount.

Feel free to re-open this task with more information in case I misunderstood what you meant.

**Comment by sdespont** [comment]
Ok, you are right. I found an example here : https://www.qr-invoice.ch/fr/documentation/exemples-de-qr-factures/
