### ISSUE TITLE
Use of own templates in HtmlOutput.php

### ISSUE THREAD

**Issue by pfitzer** [sprain/php-swiss-qr-bill#49]
At the  moment the PaymentPartTemplate in HtmlOutPut ist hard coded. How about a setter method to make it possible to use own PaymentPartTemplate to make this a bit more flexible?

something like this

````
    private $paymentPart = PaymentPartTemplate::TEMPLATE;

    public function getPaymentPart(): string
    {
        $paymentPart = $this->paymentPart;
        $paymentPart = $this->addSwissQrCodeImage($paymentPart);
        $paymentPart = $this->addInformationContent($paymentPart);
        $paymentPart = $this->addInformationContentReceipt($paymentPart);
        $paymentPart = $this->addCurrencyContent($paymentPart);
        $paymentPart = $this->addAmountContent($paymentPart);
        $paymentPart = $this->addAmountContentReceipt($paymentPart);
        $paymentPart = $this->addFurtherInformationContent($paymentPart);
        $paymentPart = $this->addPrintableContent($paymentPart);

        $paymentPart = $this->translateContents($paymentPart, $this->getLanguage());

        return $paymentPart;
    }

    public function setPaymentPart(string $paymentPart): void
    {
        $this->paymentPart = $paymentPart;
    }
````

**Comment by sprain** [comment]
> How about a setter method to make it possible to use own PaymentPartTemplate to make this a bit more flexible?

What use case do you have to use a custom template? The design is very much fixed by the specifications.

Nevertheless, you can already now write your own implementation of `AbstractOutput` and do with it whatever you want.

**Comment by pfitzer** [comment]
Yep that`s right. It`s not me working on this and colleague has no github account;)

Our problem is the CSS and the positioning in our PDFs. I tell him to use a own implementation of _AbstractOutput_.

thx for your work

**Comment by sprain** [comment]
> Our problem is the CSS and the positioning in our PDFs.

You can also override css with your own if you want :)

> I tell him to use a own implementation of AbstractOutput.

👍
