### ISSUE TITLE
Additional Information Example

### ISSUE THREAD

**Issue by rupteur** [sprain/php-swiss-qr-bill#55]
Hello,

Thanks for your project! It's really usefull :)

Could you add an "Additional Information" section example in example.php? I couldn't find how add it.

Thanks in advance.

**Comment by sdespont** [comment]
Create `AdditionalInformation `object, then set it : 

```
// Add additional information about the payment
$additionalInformation = AdditionalInformation::create('Invoice 1234568', "Billing information");
$qrBill->setAdditionalInformation($additionalInformation);
```

**Comment by sprain** [comment]
The examples will be updated with pr #53. Additional information is already ready there.

**Comment by benntfra** [comment]
Hey there,
when I use the example, the string "Billing Information" is printed in line 32 and with QR-Validation the line is marked as error with the message "the field must start with the following string: //S1". What do i wrong?
