### ISSUE TITLE
Generate QR-Bills from a CSV file

### ISSUE THREAD

**Issue by omueller** [sprain/php-swiss-qr-bill#57]
Hello, bonjour & thanks for this great project !  

Just a small question:  my goal later this year would be to generate about 20-30 QR invoices with this library (most probably over php-swiss-qr-bill-tcpdf then I guess), based on a simple CSV list (with name, address, plz, city, invoice nr, invoice description, amount, invoice+due date):  would you already have this kind of code/script around, also if just as test-script ?  

Otherwise I would be happy to try to create something on my own and share it as well.  I just want to make sure I don't redo something already existing. 

Thanks & best regards, Olivier

**Comment by sprain** [comment]
Creating a batch of qr bills from a list is not the intended feature of this library. So no, it’s not there and you would no re-do something existing. 

Of course, this library can be used as a base for what you need to build in your use-case.

**Comment by omueller** [comment]
Ok, thanks for your quick reply @sprain !
