### ISSUE TITLE
How can I generate a bill without reference? 

### ISSUE THREAD

**Issue by samuelgfeller** [sprain/php-swiss-qr-bill#65]
My client has a normal IBAN (not QR-IBAN) and needs to be able to do bills without reference number. 
When I omit the paymentReference I get the error `This value should not be null` which is normal since `src\QrBill.php:279` is validated to not be null.  
I was on the phone with PostFinance and they said QR-IBAN and Reference Nr is not mandatory for QR-Bills.   
Is there any option or something I have missed where I can configure it?

**Comment by sprain** [comment]
You must explicitly declare that you do not want to use a reference number by setting the `NON` reference type.

```php
$qrBill->setPaymentReference(
    QrBill\DataGroup\Element\PaymentReference::create(
        QrBill\DataGroup\Element\PaymentReference::TYPE_NON
    )
);
```

**Comment by sprain** [comment]
I added an example on how to create the most minimal qr bill that is possible.
https://github.com/sprain/php-swiss-qr-bill/blob/master/example/example_minimal.php

Hope this helps. Feel free to re-open this issue if you think I missed something here.

**Comment by samuelgfeller** [comment]
Exactly what I needed thank you very much for the quick response!
