### ISSUE TITLE
country code should not precede postal code

### ISSUE THREAD

**Issue by miestp** [sprain/php-swiss-qr-bill#68]
Hi, we have just finished integrating your package into our billing process and are extremely happy with your brilliant work!
One tiny detail remains to be fixed:
The two digit country code should not precede the postal code like in "CH-3013 Bern". All published examples in the specs just print it like "3013 Bern". I am aware that there is some contradiction to the rule that all payment relevant information of the QR code must be printed in the information section, but I would propose to omit the printed country code. International postal addressing is recommended in the format postal code city and COUNTRY on a separate line in capital letters, not as two digit country code any more.
Thank you so much again for this very helpful project!
Peter

**Comment by sprain** [comment]
@miestp 
First of all: Thank you very much for your sponsoring!

And thank you for this issue. I will have a look at the guidelines and check if this needs to change. It is possible that in an early version I did not want to take care of having to deal with translations of country names ;)

**Comment by gexclaude** [comment]
Have a look at https://github.com/swico/qr-bill/issues/1

**Comment by sprain** [comment]
Thanks @gexclaude!
So it was indeed undefined how to do it. Good to know!

**Comment by sprain** [comment]
https://github.com/sprain/php-swiss-qr-bill/releases/tag/v2.15 contains the fix 🥳
