### ISSUE TITLE
Test and prepare compatibility with PHP 8

### ISSUE THREAD

**Issue by sprain** [sprain/php-swiss-qr-bill#72]
PHP 8 will be released on November 26, 2020.
Is this library ready yet?

Some third-party activity to keep an eye on:
https://github.com/rdohms/phpunit-arraysubset-asserts/pull/17
https://github.com/phpspec/prophecy/issues/491
https://github.com/endroid/qr-code/issues/269
https://github.com/Bacon/BaconQrCode/pull/74 (dependency of endroid/qr-code)

**Comment by AurelienTisserand** [comment]
@sprain Maybe we could already work on PHP 7.4 compatibility ? Can you modify composer.json for allowing 7.4 ?

**Comment by sprain** [comment]
Hi @AurelienTisserand 
This library already does support PHP 7.4. That's how I run it myself on production. In addition, it runs with PHP 7.2 and PHP 7.3, which are both still actively maintained by the php community.

**Comment by AurelienTisserand** [comment]
Hi @sprain ! Thanks for your message. I encountered an issue with composer update and I first think it was due to that. I solve it. Thank you ! As soon as we will test PHP8 on our own library I will test this one too.
Have a nice day

**Comment by sprain** [comment]
PHP 8 is now supported.
https://github.com/sprain/php-swiss-qr-bill/releases/tag/v3.1
