### ISSUE TITLE
Feature Proposal: XSL-FO output

### ISSUE THREAD

**Issue by el-seirh** [sprain/php-swiss-qr-bill#76]
Hi @sprain and thanks for this super helpful library!

I'm considering adding the ability to output https://en.wikipedia.org/wiki/XSL_Formatting_Objects in order to create pdfs with that xml.

When I look at the \Sprain\SwissQrBill\PaymentPart\Output\HtmlOutput\HtmlOutput class I see that in fact most of the logic in there is not html-specific and could easily be used for other markup too. In fact only the templates themselves are html-specific and could be duplicated (written in xsl-fo instead of html).

My first idea was to rename the HtmlOutput class to something like MarkupOutput and then maybe add a parameter $outputFormat = 'html' / 'xsl-fo' to the getPaymentPart() function. With that paramter we could then just load another set of templates. The rest of alle the logic in MarkupOutput could remain the same.

What do think of that idea and do you maybe have an even more elegant one or are already working on an xsl-fo implementation?

**Comment by sprain** [comment]
> What do think of that idea and do you maybe have an even more elegant one or are already working on an xsl-fo implementation?

I have no experience with `XSL-FO`, but I think your idea sounds good.
You could build a `XslOutput` based on the `HtmlOutput`.

Thanks for your efforts!

**Comment by el-seirh** [comment]
Ok, then i think I'll do that. But just to be clear: I would need to move basically all functions out of `HtmlOutput` into some kind of more general parent `MarkupOutput` class to avoid code redundancy. The two new classes `HtmlOutput` + `XslFoOutput` then would inherit all functions from `MarkupOutput` and would only specify which templates they use.

**Comment by sprain** [comment]
> I would need to move basically all functions out of HtmlOutput into some kind of more general parent MarkupOutput class to avoid code redundancy. 

I think that sounds fine 👍

**Comment by sprain** [comment]
See #78

**Comment by sprain** [comment]
Closing along with #78.
