### ISSUE TITLE
Not generating png file – potential bug with PHP 7.4.6?

### ISSUE THREAD

**Issue by andy5489** [sprain/php-swiss-qr-bill#79]
I updated to PHP 7.4.6.
Before everything was working great, now it is no more generating the .png file.

It get stucked here:

`try {
            $qrBill->getQrCode()->writeFile(__DIR__ . '/qr1.png');
            $qrBill->getQrCode()->writeFile(__DIR__ . '/qr1.svg');
        } catch (Exception $e) {
            foreach ($qrBill->getViolations() as $violation) {
                print $violation->getMessage() . "\n";
            }
            exit;
        }`

It goes to the exception but doesn't print any message error, it just goes to exit.

I tried to generate another png file using the php functions and it works great, I have all the write permission to write to my folder.
I am doing something wrong or it is a bug with php 7.4.6?

Before I had PHP 7.3.11 and it was working perfectly

**Comment by sprain** [comment]
Hi @andy5489 – have you already tried running the `example.php` to determine whether it's your code that's broken or something with the library/php version?

**Comment by andy5489** [comment]
> Hi @andy5489 – have you already tried running the `example.php` to determine whether it's your code that's broken or something with the library/php version?

Hi @sprain, yes, also with the example.php is not working.
Everything is working good except the generating of the png/svg file. If I paste an old png/svg file and comment the generating part, everything is then working good.

**Comment by sprain** [comment]
I just installed PHP 7.4.6 and ran `example.php`. It all worked fine.

Do a `print $e->getMessage()` or `print get_class($e)` within the catch block. I suppose the issue is coming from somewhere else. The fact that no violations are presented supports this.

Feel free to let us know here afterwards or re-open this issue if you can confirm that the problem comes from within this library.

**Comment by andy5489** [comment]
> I just installed PHP 7.4.6 and ran `example.php`. It all worked fine.
> 
> Do a `print $e->getMessage()` or `print get_class($e)` within the catch block. I suppose the issue is coming from somewhere else. The fact that no violations are present supports this.
> 
> Feel free to let us know here afterwards or re-open this issue if you can confirm that the problem comes from within this library.

Thank you for your support!
In this case I will continue the analysis to see where else the problem comes from.
Thank you for all your hard work!

**Comment by sprain** [comment]
By the way: My guess would be a missing `gd-ext` in your current php build.
