### ISSUE TITLE
How do i validate a IBAN or QR-IBAN?

### ISSUE THREAD

**Issue by AneeqIftikhar** [sprain/php-swiss-qr-bill#81]
I need to know how do i do validate an IBAN or QR-IBAN before generating a payment? In the system i using this library i register the user with a QR-IBAN or IBAN and they can generate QR Codes for their clients. But On registration of the user i have no way to validate the QR-IBAN or IBAN they are entering and it can only be known when they try to generate first QR Code.

**Comment by sprain** [comment]
Hey @AneeqIftikhar - validation of an IBAN is not what this library is made for. But in the code of this library you can find how to do it 😉

Here is a good place to get started:
https://symfony.com/doc/current/reference/constraints/Iban.html
