### ISSUE TITLE
PSR-4 compatibility

### ISSUE THREAD

**Issue by tdjac0bs** [sprain/php-swiss-qr-bill#83]
I'm receiving this error:

```Deprecation Notice: Class Sprain\Tests\SwissQrBill\PaymentPart\Output\HtmlOutput\TcPdfOutputTest located in ./vendor/sprain/swiss-qr-bill/tests/PaymentPart/Output/TcPdfOutput/TcPdfOutputTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201```

It seems it's just matter of making the class name ( and namespace ) match with the file path and name.

**Comment by sprain** [comment]
Thanks! Yes, obviously the namespace of `TcPdfOutputTest` is wrong. Should be an easy fix.
