### ISSUE TITLE
Change int offset to float in pdf output, for accurate result

### ISSUE THREAD

**Issue by gaborkgabork** [sprain/php-swiss-qr-bill#86]
Please change "int $offsetX" = 0 to "float $offsetX" and for $offestY, in TcpdfOutput.php and FpdfOutput.
I think is more precise for printing, to change offset for ex by 0.5mm. 
$output = new QrBill\PaymentPart\Output\TcPdfOutput\TcPdfOutput($qrBill, 'en', $tcPdf,0,-0.5);

Thanks!

**Comment by sprain** [comment]
Do you really have the need to move the document by 0.5mm?

I would be fine with the change. PR is welcome.

**Comment by gaborkgabork** [comment]
Sorry, i explain more. I have made a precise A4 template for Indesign, for printing this bill, according the Six style guide. It fit exactly with this minor change, especially the qr-code. With my tests with TcpdfOutput, the qr-image need to be placed at $yPosQrCode =209 instead 209.5 Thanks

**Comment by sprain** [comment]
@gaborkgabork Would #99 do the job for you?

**Comment by gaborkgabork** [comment]
Yes! Thx a lot!
