### ISSUE TITLE
GD headers Version => 2.3.0

### ISSUE THREAD

**Issue by eshop-it** [sprain/php-swiss-qr-bill#87]
The library does not work with the PHP GD Extention Vers. 2.3.0

**Comment by sprain** [comment]
Hi @eshop-it, thanks for your information. Do you have details?
An issue with this would likely have to be handled in https://github.com/endroid/qr-code.

**Comment by eshop-it** [comment]
Guten Morgen Herr Reinhard,

 

vielen Dank fürs Feedbck.

 

Wir hatten ein gutfunktionierendes System. 

Am 22.8 hat der Provider ein PHP Update durgeführt.

 

Hoster:

Korrekt, der letzte PHP 7.2 Update auf dem Server Maximus war am 22.08.2020 19:15:0, PHP 7.2.32 -> 7.2.33

 

In dem Zusammenhang wurde auch die GD Extension aktualisiert.

GD library Version => 2.2.5

GD headers Version => 2.3.0

 

Da funktionierte nichts mehr. Wenn das QR.png geniert wird schmeiss der Server eine Exception.  Leider kann ich das nicht Debuggen um festzustellen wo genau der Fehler auftritt.

Wir haben die PHP Version auf 7.3 umgestellt. Da sollte laut METANET «Hoster» noch die alte GD Library 2.2.5 installiert sein und so funktioniert das System problemlos.

 

Im Zusammenhang der Fehlersuche haben wir die aktuelle Swiss QR Library installiert, was aber das Problem nicht löste.

 

Freundliche Grüsse

 

Peter Stadelmann

Geschäftsführer 

Dipl. Inf. Ing. HTL

 



 

 

eShop-IT Solutions GmbH

Arbachstrasse 2

6340 Baar

 

Tel. 041 711 08 48

 

web:  <https://www.eshop-it.ch/> https://www.eshop-it.ch/ 

 

Wir haben neue PrestaShop Module! Besuchen Sie unseren online-shop >>  <https://www.prestashop-module.ch/> https://www.prestashop-module.ch/ 

 

Folgen Sie uns auf facebook oder LinkedIn!

 

 <https://www.facebook.com/eshopit.ch>     <https://www.linkedin.com/company/eshop-itsolutions/> 

 

 

 

Von: Manuel Reinhard <notifications@github.com> 
Gesendet: Dienstag, 15. September 2020 16:10
An: sprain/php-swiss-qr-bill <php-swiss-qr-bill@noreply.github.com>
Cc: eshop-it <info@eshop-it.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [sprain/php-swiss-qr-bill] GD headers Version => 2.3.0 (#87)

 

Hi @eshop-it <https://github.com/eshop-it> , thanks for your information. Do you have details?
An issue with this would likely have to be handled in https://github.com/endroid/qr-code.

**Comment by sprain** [comment]
> Wenn das QR.png geniert wird schmeiss der Server eine Exception.

Here it gets interesting. What does the exception say and where does it originate?

**Comment by eshop-it** [comment]
Where exactly the error comes from I could not evaluate.

I have no possibility to debug on the server.

If you have an idea how to debug it I could help you.

The error message from the server:

Internal Server Error
The server encountered an internal error or misconfiguration and was
unable to complete your request. Please contact the server administrator,
and inform them of the time the error occurred and anything you might have
done that may have caused the error.
More information about this error may be available in the server error



 

Von: Manuel Reinhard <notifications@github.com> 
Gesendet: Mittwoch, 16. September 2020 13:28
An: sprain/php-swiss-qr-bill <php-swiss-qr-bill@noreply.github.com>
Cc: eshop-it <info@eshop-it.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [sprain/php-swiss-qr-bill] GD headers Version => 2.3.0 (#87)

 

Wenn das QR.png geniert wird schmeiss der Server eine Exception.

Here it gets interesting. What does the exception say and where does it originate?

**Comment by sprain** [comment]
> The error message from the server:

Based on this basic error message, how do you know that the error comes from GD? You would find more specific information in the error log on the server.

I am currently not able to have a test environment with GD 2.3 so if any information about successful or unsuccessful usage with that version is welcome here.

**Comment by eshop-it** [comment]
We could not find any information in the log

If GD 2.2 is installed on the server everything works.

If the GD 2.3 is installed this error occurs

 

Von: Manuel Reinhard <notifications@github.com> 
Gesendet: Mittwoch, 16. September 2020 14:17
An: sprain/php-swiss-qr-bill <php-swiss-qr-bill@noreply.github.com>
Cc: eshop-it <info@eshop-it.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [sprain/php-swiss-qr-bill] GD headers Version => 2.3.0 (#87)

 

The error message from the server:

Based on this basic error message, how do you know that the error comes from GD? You would find more specific information in the error log on the server.

I am currently not able to have a test environment with GD 2.3 so if any information about successful or unsuccessful usage with that version is welcome here.

**Comment by tobiv** [comment]
I happen to run PHP 7.4.10 with GD library v2.3.0 and GD headers v2.3.0: writing image files as well as HTML output works for me.

**Comment by dterumalai** [comment]
Hi @sprain, 
First thanks a lot for this very cool package. I've also encountered the same issue as described above while trying the example.php with the following config:

- PHP 8.0
- GD 2.30

It triggered:
```
[2020-12-25 16:10:51] local.ERROR: Unable to generate image: check your GD installation {"exception":"[object] (Endroid\\QrCode\\Exception\\GenerateImageException(code: 0): Unable to generate image: check your GD installation at /var/www/html/vendor/endroid/qr-code/src/Writer/PngWriter.php:74)
[stacktrace]
#0 /var/www/html/vendor/endroid/qr-code/src/Writer/PngWriter.php(61): Endroid\\QrCode\\Writer\\PngWriter->createBaseImage()
#1 /var/www/html/vendor/endroid/qr-code/src/Writer/PngWriter.php(30): Endroid\\QrCode\\Writer\\PngWriter->createImage()
#2 /var/www/html/vendor/endroid/qr-code/src/Writer/AbstractWriter.php(74): Endroid\\QrCode\\Writer\\PngWriter->writeString()
#3 /var/www/html/vendor/endroid/qr-code/src/QrCode.php(407): Endroid\\QrCode\\Writer\\AbstractWriter->writeFile()
#4 /var/www/html/vendor/sprain/swiss-qr-bill/src/QrCode/QrCode.php(25): Endroid\\QrCode\\QrCode->writeFile()
``` 

(same with `SvgWriter`)

When I downgraded my PHP version to 7.4, the issue was gone.

**Comment by sprain** [comment]
> When I downgraded my PHP version to 7.4, the issue was gone.

Ok, that's pretty good already, since this library does not yet support PHP 8.0. See #72.

**Comment by pableu** [comment]
I guess this can now be closed @sprain.

**Comment by sprain** [comment]
@pableu I am not sure. Can we confirm it works with GD 2.3?

**Comment by pableu** [comment]
We weren't affected by this issue, but we now have PHP 8.x and GD 2.3.0 in production and I don't see any problems. So I'm not in an ideal situation to give a definitive answer.

**Comment by sprain** [comment]
Likely no issues with GD 2.3.
Otherwise feel free to re-open with new information.
