### ISSUE TITLE
Reference  BESR-ID

### ISSUE THREAD

**Issue by ningappa** [sprain/php-swiss-qr-bill#88]
Hi @sprain .

Do you any reference to validate this comment.?

https://github.com/sprain/php-swiss-qr-bill/blob/7aa1e62c8520d9a587d950c22be5de15888f1081/example/example.php#L60

Because, few of our customers qr payments got failed. I was trying to understand if this is the cause of problem.

**Comment by sprain** [comment]
[Docs, Chapter 2.12.1](https://github.com/sprain/php-swiss-qr-bill/blob/master/docs/specs/ig-qr-bill-en-v2.1.pdf): «The structure of the QR reference corresponds to that of the ISR reference»
An ISR reference starts with a 6-8 digit code which depends on your bank. [You can find a manual for many Swiss banks online.](https://www.google.ch/search?client=safari&ei=uVpvX6-BE86IrwTlopngAg&q=esr+handbuch&oq=esr+handbuch&gs_lcp=CgZwc3ktYWIQAzICCAAyAggAMgQIABAeMgYIABAFEB4yBggAEAgQHjIGCAAQCBAeOgQIABBHOgYIABAHEB46CAgAEAgQBxAeUJwTWOEVYNkXaABwAngAgAFOiAGXAZIBATKYAQCgAQGqAQdnd3Mtd2l6yAEIwAEB&sclient=psy-ab&ved=0ahUKEwjvwdiQjofsAhVOxIsKHWVRBiwQ4dUDCAw&uact=5)

Summed up its like stated in the comment, or if you prefer an additional source, as explained by [bexio](https://support.bexio.com/hc/de/articles/206487948-Oranger-Einzahlungsschein-einrichten-ESR-):

_«Die BESR-ID (Banknummer) ist in der Regel eine 6- bis 8-stellige Nummer ohne Sonderzeichen und Bindestriche – diese sieht zum Beispiel so aus: 123456. Je nach Bank werden diese beiden Nummern unterschiedlich benannt. Bei der PostFinance wird bspw. keine BESR-ID benötigt, weil die Postcheck-Kontonummer eine eindeutige Nummer ist. Die beiden notwendigen Zahlenkombinationen erhalten Sie direkt von Ihrer Bank.»_

Feel free to re-open this issue if this does not help you.
