### ISSUE TITLE
Feature Proposal: Pdflib-Output

### ISSUE THREAD

**Issue by pableu** [sprain/php-swiss-qr-bill#89]
My company uses [PDFLib](https://www.pdflib.com/) to generate a multitude of PDFs. 

I'm considering adding PDFLib output to this library. Would you be interested in a PR?

**Comment by sprain** [comment]
I see that PdfLib requires a license. If that‘s correct I would not be able to test and use it and I would not see it as part of this library. Of course, you can still use the library and publish a `PdflibOutput` on your own, if you wish.

Feel free to re-open this issue if I missed something here.

**Comment by pableu** [comment]
Oh, you‘re right, I didn‘t think of that. You can actually install and use it without a license and it will just add a full page watermark (saying „pdflib“ or „unlicensed“ or something like that). 

It‘s certainly not simple to test, also because it‘s a PHP extension and not simply a composer package. 

What do you think?

**Comment by sprain** [comment]
Thanks for the extended information.

It still looks like something that is out of scope for this library. I would not be able to support it in the long term.
