### ISSUE TITLE
Problem on installation - requirements not resolved

### ISSUE THREAD

**Issue by lahode** [sprain/php-swiss-qr-bill#9]
Hello,

When executing composer require sprain/swiss-qr-bill, I meet the following error (happening on master and html-output branch).

  Problem 1
    - Installation request for sprain/swiss-qr-bill dev-master -> satisfiable by sprain/swiss-qr-bill[dev-master].
    - Can only install one of: sprain/swiss-qr-bill[v0.4, dev-master].
    - Installation request for sprain/swiss-qr-bill ^0.4.0 -> satisfiable by sprain/swiss-qr-bill[v0.4].

Thank you in advance for your help

**Comment by sprain** [comment]
Since this library will need to be updated to the implentation guidelines v2.0 anyways, I am going to close this.

Feel free to report back if it's still a current issue for you. Seeing your whole composer.json file would help then.
