### ISSUE TITLE
PDF generation failed

### ISSUE THREAD

**Issue by marten66** [sprain/php-swiss-qr-bill#92]
I got this error message: Fatal error: Uncaught Error: Class 'Fpdf\Fpdf' not found in... I installed the php-swiss-qr-bill by composer. QR Image creation does work well. 

![qrBill](https://user-images.githubusercontent.com/60956844/95549050-b8b6c780-0a06-11eb-99a8-5455967ddb55.jpg)

**Comment by Franco2911** [comment]
Did you installed FPDF?
`composer require fpdf/fpdf`
This package is only suggested in php-swiss-qr-bill package.

**Comment by marten66** [comment]
Yes but manually. Now I've installed it with composer. It works now. Thank you.
