### ISSUE TITLE
use php-swiss-qr-bill with PHP 7.0.3

### ISSUE THREAD

**Issue by belgacemkh** [sprain/php-swiss-qr-bill#93]
Can you tell me which php-swiss-qr-bill's version works well with a PHP 7.0.3 environment?
thank you in advance

**Comment by sprain** [comment]
This library always required at least PHP 7.1.

[PHP 7.0 reached end of life almost 2 years ago](https://www.php.net/supported-versions.php). You should consider upgrading.
