### ISSUE TITLE
Error with the SCOR reference when paying by post: spaces should be removed

### ISSUE THREAD

**Issue by Franco2911** [sprain/php-swiss-qr-bill#95]
Hello,
One of our customer had this error when trying to paye at the post.

_Reference value <RF71 1122> different of type < SCOR > reference._

Have you any idea of what is the problem?

Thank you for help

**Comment by sprain** [comment]
To check whether there is a potential bug in the qr bill, you could validate this specific qr code on https://validation.iso-payments.ch/qrrechnung

**Comment by sprain** [comment]
If publicly shareable, you could also post the qr code here and I can run it through the validator for you.

**Comment by Franco2911** [comment]
This what we received from validator...
```
Invalid structure of ISO creditor reference 
[Line 0044]
Open Documentation

0043 <Tp>SCOR</Tp>
0044 <Ref>RF98 1121</Ref>
```

```
Status |   | D
-- | -- | --
Definition |   | Note: The structured reference is either a QR reference or an ISO 11649 Creditor Reference
Field name |   | Reference
Field Specific Definitions |   | Maximum 27 characters, alphanumeric; must be filled if a QR-IBAN is used.QR reference: 27 characters, numeric, check sum calculation according to Modulo 10 recursive (27th position of the reference)Creditor Reference (ISO 11649): max 25 characters, alphanumericThe element may not be filled for the NON reference type.
Line # |   | 29 | 29
29
```
It seems that the SCOR reference must be to another place, if i understand right.
Thank you for any suggestion

**Comment by Franco2911** [comment]
I found the error...
the SCOR reference cannot be formatted as RF78 1121 but must be used without spaces.
This error does not come from your library but from our code.

Maybe it would be useful to add a validator for this.

You can close this issue, thanks for your support.

**Comment by sprain** [comment]
Thanks for debugging this!

I think the best way would be to remove spaces in any reference number in `Sprain\SwissQrBill\DataGroup\Element\ PaymentReference` by default.  There already is a `getFormattedReference()` method which then will add spaces where required again.
